# Generated by Django 5.1.3 on 2026-01-20 08:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "permissions": [
                    (
                        "can_view_personal_data",
                        "[!WARNING!] Can View User Personal Data",
                    )
                ]
            },
        ),
    ]
