# Generated by Django 5.1.3 on 2025-05-27 12:37

import uuid

import bm.utils
import django.db.models.deletion
from django.db import migrations, models


def migrate_system_type(apps, schema_editor):
    PaymentTransaction = apps.get_model("payment", "PaymentTransaction")
    for transaction in PaymentTransaction.objects.select_related(
        "wallet__wallet__system"
    ).all():
        transaction.system_type = transaction.wallet.wallet.system.type
        transaction.save(update_fields=["system_type"])


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0022_customer_remove_paymenttransaction_customer_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventLog",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("error", "Error"),
                            ("callback_sending_attempt", "Callback Sending Attempt"),
                            ("external_api_request", "External API Request"),
                            ("callback_retry_requested", "Callback Retry Requested"),
                            ("important", "!!! Important !!!"),
                            (
                                "transaction_actualization",
                                "Transaction Actualization (Admin)",
                            ),
                            (
                                "transaction_set_status",
                                "Transaction Set Status (Admin)",
                            ),
                            (
                                "withdrawal_stuck_in_processing",
                                "Withdrawal Stuck in Processing",
                            ),
                            ("info", "Info"),
                            (
                                "customer_redirect_received",
                                "Customer Redirect Received",
                            ),
                            ("charge_back", "Charge Back"),
                            ("charge_back_reversal", "Charge Back Reversal"),
                            (
                                "create_deposit_instruction",
                                "Create Deposit Instruction",
                            ),
                            ("payout_refund", "Payout Refund"),
                            ("revert_to_initial", "Revert to Initial Status"),
                        ],
                        max_length=255,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "extra",
                    models.JSONField(default=dict, encoder=bm.utils.BMJsonEncoder),
                ),
                ("request_id", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "system_type",
                    models.CharField(
                        choices=[
                            ("spei_stp", "SPEI STP"),
                            ("stp_codi", "STP CODI"),
                            ("d24_mercadopago", "D24 MercadoPago"),
                            ("paycash", "PayCash"),
                            ("paypal", "PayPal"),
                            ("bitso_spei", "Bitso SPEI"),
                            ("appex", "Appex"),
                            ("conekta_oxxo", "Conekta OXXO"),
                        ],
                        max_length=200,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="customer",
            name="extra",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="customer",
            name="phone",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="paymenttransaction",
            name="system_type",
            field=models.CharField(
                choices=[
                    ("spei_stp", "SPEI STP"),
                    ("stp_codi", "STP CODI"),
                    ("d24_mercadopago", "D24 MercadoPago"),
                    ("paycash", "PayCash"),
                    ("paypal", "PayPal"),
                    ("bitso_spei", "Bitso SPEI"),
                    ("appex", "Appex"),
                    ("conekta_oxxo", "Conekta OXXO"),
                ],
                default=None,
                max_length=200,
                null=True,
            ),
            preserve_default=False,
        ),
        migrations.RunPython(migrate_system_type, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="paymenttransaction",
            name="system_type",
            field=models.CharField(
                choices=[
                    ("spei_stp", "SPEI STP"),
                    ("stp_codi", "STP CODI"),
                    ("paycash", "PayCash"),
                    ("paypal", "PayPal"),
                    ("bitso_spei", "Bitso SPEI"),
                ],
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="paymentsystem",
            name="type",
            field=models.CharField(
                choices=[
                    ("spei_stp", "SPEI STP"),
                    ("stp_codi", "STP CODI"),
                    ("d24_mercadopago", "D24 MercadoPago"),
                    ("paycash", "PayCash"),
                    ("paypal", "PayPal"),
                    ("bitso_spei", "Bitso SPEI"),
                    ("appex", "Appex"),
                    ("conekta_oxxo", "Conekta OXXO"),
                ],
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="paymenttransactioneventlog",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("error", "Error"),
                    ("callback_sending_attempt", "Callback Sending Attempt"),
                    ("external_api_request", "External API Request"),
                    ("callback_retry_requested", "Callback Retry Requested"),
                    ("important", "!!! Important !!!"),
                    ("transaction_actualization", "Transaction Actualization (Admin)"),
                    ("transaction_set_status", "Transaction Set Status (Admin)"),
                    (
                        "withdrawal_stuck_in_processing",
                        "Withdrawal Stuck in Processing",
                    ),
                    ("info", "Info"),
                    ("customer_redirect_received", "Customer Redirect Received"),
                    ("charge_back", "Charge Back"),
                    ("charge_back_reversal", "Charge Back Reversal"),
                    ("create_deposit_instruction", "Create Deposit Instruction"),
                    ("payout_refund", "Payout Refund"),
                    ("revert_to_initial", "Revert to Initial Status"),
                ],
                max_length=255,
            ),
        ),
        migrations.CreateModel(
            name="BitsoTransactionExtraData",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "clave_rastreo",
                    models.CharField(
                        db_index=True, max_length=64, verbose_name="Clave de rastreo"
                    ),
                ),
                (
                    "transaction",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="payment.paymenttransaction",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CustomerDepositInstruction",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "system_type",
                    models.CharField(
                        choices=[
                            ("spei_stp", "SPEI STP"),
                            ("stp_codi", "STP CODI"),
                            ("d24_mercadopago", "D24 MercadoPago"),
                            ("paycash", "PayCash"),
                            ("paypal", "PayPal"),
                            ("bitso_spei", "Bitso SPEI"),
                            ("appex", "Appex"),
                            ("conekta_oxxo", "Conekta OXXO"),
                        ],
                        max_length=200,
                    ),
                ),
                (
                    "deposit_account_number",
                    models.CharField(max_length=255, unique=True),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="payment.customer",
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="payment.wallet"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="paymenttransaction",
            name="customer_instruction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="payment.customerdepositinstruction",
            ),
        ),
        migrations.CreateModel(
            name="CustomerExternalPaymentSystemAccount",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("uuid", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("unique_account_number", models.CharField(max_length=255)),
                (
                    "system_type",
                    models.CharField(
                        choices=[
                            ("spei_stp", "SPEI STP"),
                            ("stp_codi", "STP CODI"),
                            ("d24_mercadopago", "D24 MercadoPago"),
                            ("paycash", "PayCash"),
                            ("paypal", "PayPal"),
                            ("bitso_spei", "Bitso SPEI"),
                            ("appex", "Appex"),
                            ("conekta_oxxo", "Conekta OXXO"),
                        ],
                        max_length=200,
                    ),
                ),
                ("extra", models.JSONField(blank=True, default=dict)),
                ("active", models.BooleanField(default=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="payment.customer",
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="payment.wallet"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="paymenttransaction",
            name="customer_external_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="payment.customerexternalpaymentsystemaccount",
            ),
        ),
        migrations.AddConstraint(
            model_name="paymenttransaction",
            constraint=models.UniqueConstraint(
                fields=("system_type", "id_in_payment_system"),
                name="unique_transaction_id_in_payment_system",
            ),
        ),
        migrations.AddField(
            model_name="eventlog",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="payment.customer",
            ),
        ),
        migrations.AddField(
            model_name="eventlog",
            name="merchant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="payment.merchant",
            ),
        ),
        migrations.AddConstraint(
            model_name="customerdepositinstruction",
            constraint=models.UniqueConstraint(
                fields=("system_type", "deposit_account_number"),
                name="cusdepoins_sys_account_number",
            ),
        ),
        migrations.AddConstraint(
            model_name="customerexternalpaymentsystemaccount",
            constraint=models.UniqueConstraint(
                fields=("system_type", "wallet", "unique_account_number"),
                name="unique_customer_wallet",
            ),
        ),
        migrations.AlterField(
            model_name="paymenttransaction",
            name="system_type",
            field=models.CharField(
                choices=[
                    ("spei_stp", "SPEI STP"),
                    ("stp_codi", "STP CODI"),
                    ("d24_mercadopago", "D24 MercadoPago"),
                    ("paycash", "PayCash"),
                    ("paypal", "PayPal"),
                    ("bitso_spei", "Bitso SPEI"),
                    ("appex", "Appex"),
                    ("conekta_oxxo", "Conekta OXXO"),
                ],
                max_length=200,
            ),
        ),
    ]
