# Generated by Django 5.1.3 on 2025-11-25 07:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0036_customer_risk_control_merchant_risk_control_and_more"),
        ("payment", "0037_merge_20251021_1124"),
    ]

    operations = []
