# Generated by Django 5.1.3 on 2025-12-01 13:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0037_paymenttransaction_bitso_spei_lookup_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="risk_control",
            field=models.BooleanField(
                default=False,
                help_text="If True, Risk Limits will be checked for this customer",
            ),
        ),
        migrations.AddField(
            model_name="merchant",
            name="risk_control",
            field=models.BooleanField(
                default=False,
                help_text="If True, Risk Limits will be checked for this merchant",
            ),
        ),
        migrations.AddField(
            model_name="wallet",
            name="risk_control",
            field=models.BooleanField(
                default=False,
                help_text="If True, Risk Limits will be checked for this wallet",
            ),
        ),
    ]
