# Generated by Django 5.1.3 on 2026-01-12 06:14

import rozert_pay.common.encryption
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0040_merge_20260109_1120"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="email",
            field=models.EmailField(
                blank=True, db_column="email", max_length=254, null=True
            ),
        ),
        migrations.RenameField(
            model_name="customer",
            old_name="email",
            new_name="_email",
        ),
        migrations.AlterField(
            model_name="customer",
            name="extra",
            field=models.JSONField(blank=True, db_column="extra", default=dict),
        ),
        migrations.RenameField(
            model_name="customer",
            old_name="extra",
            new_name="_extra",
        ),
        migrations.AlterField(
            model_name="customer",
            name="phone",
            field=models.CharField(
                blank=True, db_column="phone", max_length=255, null=True
            ),
        ),
        migrations.RenameField(
            model_name="customer",
            old_name="phone",
            new_name="_phone",
        ),
        migrations.AlterField(
            model_name="wallet",
            name="credentials",
            field=rozert_pay.common.encryption.EncryptedField(db_column="credentials"),
        ),
        migrations.RenameField(
            model_name="wallet",
            old_name="credentials",
            new_name="_credentials",
        ),
        migrations.AddField(
            model_name="customer",
            name="email_determenistic_hash",
            field=rozert_pay.common.encryption.DetermenisticHashField(
                blank=True,
                deterministic_hash_version="v1",
                field_type="string",
                key_set_id=rozert_pay.common.encryption.KeySetId["PII_HASH"],
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="email_encrypted",
            field=rozert_pay.common.encryption.EncryptedFieldV2(
                blank=True,
                encryption_version="v1",
                field_type="string",
                key_set_id=rozert_pay.common.encryption.KeySetId["PII"],
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="extra_encrypted",
            field=rozert_pay.common.encryption.EncryptedFieldV2(
                blank=True,
                encryption_version="v1",
                field_type="json",
                key_set_id=rozert_pay.common.encryption.KeySetId["PII"],
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="phone_encrypted",
            field=rozert_pay.common.encryption.EncryptedFieldV2(
                blank=True,
                encryption_version="v1",
                field_type="string",
                key_set_id=rozert_pay.common.encryption.KeySetId["PII"],
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="phone_hash",
            field=rozert_pay.common.encryption.DetermenisticHashField(
                blank=True,
                deterministic_hash_version="v1",
                field_type="string",
                key_set_id=rozert_pay.common.encryption.KeySetId["PII_HASH"],
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="wallet",
            name="credentials_encrypted",
            field=rozert_pay.common.encryption.EncryptedFieldV2(
                blank=True,
                encryption_version="v1",
                field_type="json",
                key_set_id=rozert_pay.common.encryption.KeySetId["CREDENTIALS"],
                null=True,
            ),
        ),
    ]
