# Generated by Django 5.1.3 on 2026-01-16 08:52

import rozert_pay.common.encryption
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0041_alter_customer_email_rename_email_customer__email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customercard",
            name="card_data",
            field=rozert_pay.common.encryption.EncryptedField(db_column="card_data"),
        ),
        migrations.RenameField(
            model_name="customercard",
            old_name="card_data",
            new_name="_card_data",
        ),
        migrations.AlterField(
            model_name="wallet",
            name="credentials",
            field=rozert_pay.common.encryption.EncryptedField(db_column="credentials"),
        ),
        migrations.RenameField(
            model_name="wallet",
            old_name="credentials",
            new_name="_credentials",
        ),
        migrations.AddField(
            model_name="customercard",
            name="card_data_encrypted",
            field=rozert_pay.common.encryption.EncryptedFieldV2(
                blank=True,
                encryption_version="v1",
                field_type="json",
                key_set_id=rozert_pay.common.encryption.KeySetId["CARD_DATA"],
                null=True,
                view_permission=CommonUserPermissions.CAN_VIEW_CUSTOMER_CARD_DATA,
            ),
        ),
        migrations.AddField(
            model_name="wallet",
            name="credentials_encrypted",
            field=rozert_pay.common.encryption.EncryptedFieldV2(
                blank=True,
                encryption_version="v1",
                field_type="json",
                key_set_id=rozert_pay.common.encryption.KeySetId["CREDENTIALS"],
                null=True,
                view_permission=(
                    ("app", "payment"),
                    ("name", "can_view_wallet_credentials"),
                    ("display_name", "[!WARNING!] Can view Wallet Credentials"),
                ),
            ),
        ),
    ]
