# Generated by Django 5.1.3 on 2026-01-09 13:15

import rozert_pay.common.encryption
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0041_merge_20260109_1315"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallet",
            name="credentials",
            field=rozert_pay.common.encryption.EncryptedField(db_column="credentials"),
        ),
        migrations.RenameField(
            model_name="wallet",
            old_name="credentials",
            new_name="_credentials",
        ),
        migrations.AddField(
            model_name="wallet",
            name="credentials_encrypted",
            field=rozert_pay.common.encryption.EncryptedFieldV2(
                blank=True,
                encryption_version="v1",
                field_type="json",
                key_set_id=rozert_pay.common.encryption.KeySetId["CREDENTIALS"],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="extra_encrypted",
            field=rozert_pay.common.encryption.EncryptedFieldV2(
                blank=True,
                encryption_version="v1",
                field_type="json",
                key_set_id=rozert_pay.common.encryption.KeySetId["PII"],
                null=True,
            ),
        ),
    ]
