# Generated by Django 5.1.3 on 2026-01-12 07:10

import rozert_pay.common.encryption
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0042_alter_wallet_credentials_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customercard",
            name="card_data",
            field=rozert_pay.common.encryption.EncryptedField(db_column="card_data"),
        ),
        migrations.RenameField(
            model_name="customercard",
            old_name="card_data",
            new_name="_card_data",
        ),
        migrations.AddField(
            model_name="customercard",
            name="card_data_encrypted",
            field=rozert_pay.common.encryption.EncryptedFieldV2(
                blank=True,
                encryption_version="v1",
                field_type="json",
                key_set_id=rozert_pay.common.encryption.KeySetId["CARD_DATA"],
                null=True,
                view_permission=CommonUserPermissions.CAN_VIEW_CUSTOMER_CARD_DATA,
            ),
        ),
    ]
