# Generated by Django 5.1.3 on 2025-11-18 12:49

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FeatureFlag",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        choices=[("risk_control_enabled", "Risk control")],
                        max_length=255,
                        unique=True,
                    ),
                ),
                ("status", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RunPython(
            code=create_risk_control_feature_flag,
            reverse_code=reverse_create_risk_control_feature_flag,
        ),
    ]


# Generated by Django 5.1.3 on 2025-11-18 10:45



class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FeatureFlag",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        choices=FeatureFlagName.choices,
                        max_length=255,
                    ),
                ),
                ("status", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RunPython(
            code=create_risk_control_feature_flag,
            reverse_code=reverse_create_risk_control_feature_flag,
        ),
    ]
