# Generated by Django 5.1.3 on 2025-11-18 10:45

from django.db import migrations, models
from rozert_pay.feature_flags.const import FeatureFlagName


def create_risk_control_feature_flag(apps, schema_editor):
    FeatureFlag = apps.get_model("feature_flags", "FeatureFlag")
    FeatureFlag.objects.create(
        name=FeatureFlagName.RISK_CONTROL_ENABLED,
        status=False,
    )


def reverse_create_risk_control_feature_flag(apps, schema_editor):
    FeatureFlag = apps.get_model("feature_flags", "FeatureFlag")
    FeatureFlag.objects.filter(name=FeatureFlagName.RISK_CONTROL_ENABLED).delete()


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FeatureFlag",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        choices=FeatureFlagName.choices,
                        max_length=255,
                    ),
                ),
                ("status", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RunPython(
            code=create_risk_control_feature_flag,
            reverse_code=reverse_create_risk_control_feature_flag,
        ),
    ]
