# Generated by Django 5.1.3 on 2025-11-18 10:45

from django.db import migrations, models


def create_risk_control_feature_flag(apps, schema_editor):
    FeatureFlag = apps.get_model("feature_flags", "FeatureFlag")
    FeatureFlag.objects.create(
        name="risk_control_enabled",
        status=False,
    )


def reverse_create_initial_feature_flags(apps, schema_editor):
    FeatureFlag = apps.get_model("feature_flags", "FeatureFlag")
    FeatureFlag.objects.filter(name="risk_control_enabled").delete()


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FeatureFlag",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        choices=[("risk_control_enabled", "Risk control")],
                        max_length=255,
                    ),
                ),
                ("status", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RunPython(
            create_risk_control_feature_flag,
            reverse_create_initial_feature_flags,
        ),
    ]
