# Generated by Django 5.1.3 on 2025-09-03 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("payment", "0035_alter_eventlog_event_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DBAuditItem",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("operation_time", models.DateTimeField()),
                (
                    "system_type",
                    models.CharField(
                        choices=[
                            ("spei_stp", "SPEI STP"),
                            ("stp_codi", "STP CODI"),
                            ("d24_mercadopago", "D24 MercadoPago"),
                            ("paycash", "PayCash"),
                            ("paypal", "PayPal"),
                            ("bitso_spei", "Bitso SPEI"),
                            ("appex", "Appex"),
                            ("ilixium", "Ilixium"),
                            ("conekta_oxxo", "Conekta OXXO"),
                            ("cardpay_cards", "Cardpay Cards"),
                            ("cardpay_applepay", "Cardpay Applepay"),
                        ],
                        max_length=200,
                    ),
                ),
                (
                    "operation_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                            ("charged_back", "Charged Back"),
                            ("charged_back_reversal", "Charged Back Reversal"),
                        ],
                        max_length=255,
                    ),
                ),
                ("extra", models.JSONField()),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="payment.paymenttransaction",
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="payment.wallet",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["wallet", "-id"], name="idx_dbaudit_wt_id")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("operation_time", "transaction"),
                        name="uq_dbaudit_optime_trx",
                    )
                ],
            },
        ),
    ]
