# Generated by Django 5.1.3 on 2025-09-19 09:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payment_audit", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dbaudititem",
            options={"verbose_name": "Audit Items"},
        ),
    ]
