# Generated by Django 5.1.3 on 2025-12-08 16:26

from django.db import migrations, models
from rozert_pay.common.const import PaymentSystemType


class Migration(migrations.Migration):
    dependencies = [
        ("payment_audit", "0002_alter_dbaudititem_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dbaudititem",
            name="system_type",
            field=models.CharField(
                choices=PaymentSystemType.choices,
                max_length=200,
            ),
        ),
    ]
