from rozert_pay.common.const import TransactionStatus

IGNORED_CALLBACK_EVENTS = [
    "charge.under_fraud_review",
    "charge.fraudulent",
    "charge.preauthorized",
    "charge.reversed",
    "charge.pending_confirmation",
    "customer.created",
    "customer.updated",
    "customer.deleted",
    "webhook.created",
    "webhook.updated",
    "webhook.deleted",
    "charge.chargeback.created",
    "charge.chargeback.updated",
    "charge.chargeback.under_review",
    "charge.chargeback.lost",
    "charge.chargeback.won",
    "payout.created",
    "payout.retrying",
    "payout.paid_out",
    "payout.failed",
    "plan.created",
    "plan.updated",
    "plan.deleted",
    "subscription.created",
    "subscription.paused",
    "subscription.resumed",
    "subscription.canceled",
    "subscription.expired",
    "subscription.updated",
    "subscription.paid",
    "subscription.payment_failed",
    "payee.created",
    "payee.updated",
    "payee.deleted",
    "payee.payout_method.created",
    "payee.payout_method.updated",
    "payee.payout_method.deleted",
    "charge.score_updated",
    "receipt.created",
    "webhook_ping",
    "inbound_payment.lookup",
    "inbound_payment.payment_attempt",
]
PROCESSING_CALLBACK_EVENTS = [
    "order.canceled",
    "order.charged_back",
    "order.created",
    "order.expired",
    "order.fraudulent",
    "order.under_fraud_review",
    "order.paid",
    "order.partially_refunded",
    "order.pending_payment",
    "order.pre_authorized",
    "order.refunded",
    "order.updated",
    "order.voided",
    "order.declined",
    "charge.paid",
    "charge.refunded",
    "charge.declined",
    "charge.canceled",
    "charge.expired",
]
PAYMENT_STATUSES_MAPPING: dict[str, TransactionStatus] = {
    "pending_payment": TransactionStatus.PENDING,
    "pending_confirmation": TransactionStatus.PENDING,
    "declined": TransactionStatus.FAILED,
    "expired": TransactionStatus.FAILED,
    "canceled": TransactionStatus.FAILED,
    "paid": TransactionStatus.SUCCESS,
    "refunded": TransactionStatus.CHARGED_BACK,
}

CONEKTA_IP_ADDRESSES = [
    "52.44.103.21",
    "52.55.241.130",
]
