# Generated by Django 5.1.3 on 2025-09-17 11:13

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("limits", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="customerlimit",
            name="notification_groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="Группы пользователей, которые будут получать уведомления об этом алерте.",
                related_name="customer_limits_to_notify",
                to="auth.group",
            ),
        ),
        migrations.AddField(
            model_name="customerlimit",
            name="slack_channel_override",
            field=models.CharField(
                blank=True,
                help_text="Переопределить стандартный Slack-канал для уведомлений.",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="limitalert",
            name="acknowledged_by",
            field=models.ManyToManyField(
                blank=True,
                related_name="acknowledged_alerts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Acknowledged by",
            ),
        ),
        migrations.AddField(
            model_name="limitalert",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="limitalert",
            name="is_notified",
            field=models.BooleanField(
                default=False,
                help_text="Indicates whether a notification was sent to Slack",
                verbose_name="Notification sent to Slack",
            ),
        ),
        migrations.AddField(
            model_name="limitalert",
            name="notification_groups",
            field=models.ManyToManyField(
                blank=True,
                related_name="alerts_to_notify",
                to="auth.group",
                verbose_name="Notification Groups",
            ),
        ),
        migrations.AddField(
            model_name="limitalert",
            name="notification_text",
            field=models.TextField(
                blank=True,
                help_text="Notification text sent to Slack",
                null=True,
                verbose_name="Notification text",
            ),
        ),
        migrations.AddField(
            model_name="merchantlimit",
            name="notification_groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="Группы пользователей, которые будут получать уведомления об этом алерте.",
                related_name="merchant_limits_to_notify",
                to="auth.group",
            ),
        ),
        migrations.AddField(
            model_name="merchantlimit",
            name="slack_channel_override",
            field=models.CharField(
                blank=True,
                help_text="Переопределить стандартный Slack-канал для уведомлений.",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="customerlimit",
            name="active",
            field=models.BooleanField(
                default=True, help_text="Limit status, enabled or disabled"
            ),
        ),
        migrations.AlterField(
            model_name="customerlimit",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="client_limits",
                to="payment.customer",
                verbose_name="Client",
            ),
        ),
        migrations.AlterField(
            model_name="customerlimit",
            name="decline_on_exceed",
            field=models.BooleanField(
                default=False,
                help_text="Enable automatic rejection of operations that exceed the limit",
                verbose_name="Reject on limit exceed",
            ),
        ),
        migrations.AlterField(
            model_name="customerlimit",
            name="description",
            field=models.TextField(
                blank=True, help_text="Limit description set by the user"
            ),
        ),
        migrations.AlterField(
            model_name="customerlimit",
            name="is_critical",
            field=models.BooleanField(
                default=False,
                help_text="Escalates the alert to a critical notification",
                verbose_name="Critical limit",
            ),
        ),
        migrations.AlterField(
            model_name="customerlimit",
            name="max_failed_operations",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                verbose_name="Maximum number of failed operations per period",
            ),
        ),
        migrations.AlterField(
            model_name="customerlimit",
            name="max_operation_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Maximum amount allowed for a single operation",
                max_digits=20,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                verbose_name="Максимальная сумма одной операции",
            ),
        ),
        migrations.AlterField(
            model_name="customerlimit",
            name="max_successful_operations",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                verbose_name="Maximum number of successful operations per period",
            ),
        ),
        migrations.AlterField(
            model_name="customerlimit",
            name="min_operation_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Minimum amount allowed for a single operation",
                max_digits=20,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                verbose_name="Минимальная сумма одной операции",
            ),
        ),
        migrations.AlterField(
            model_name="customerlimit",
            name="period",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1h", "1 Hour"),
                    ("24h", "24 Hours"),
                    ("beginning_of_hour", "Beginning of Hour"),
                    ("beginning_of_day", "Beginning of Day"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="customerlimit",
            name="total_successful_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Maximum total amount of all successful operations for the specified period",
                max_digits=20,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                verbose_name="Total amount of successful operations per period",
            ),
        ),
        migrations.AlterField(
            model_name="merchantlimit",
            name="active",
            field=models.BooleanField(
                default=True, help_text="Status of the limit: enabled or disabled"
            ),
        ),
        migrations.AlterField(
            model_name="merchantlimit",
            name="decline_on_exceed",
            field=models.BooleanField(
                default=False, help_text="Decline operation if limit is exceeded"
            ),
        ),
        migrations.AlterField(
            model_name="merchantlimit",
            name="description",
            field=models.TextField(
                blank=True, help_text="User-defined limit description"
            ),
        ),
        migrations.AlterField(
            model_name="merchantlimit",
            name="is_critical",
            field=models.BooleanField(
                default=False,
                help_text="Escalate alert to critical notifications category",
            ),
        ),
        migrations.AlterField(
            model_name="merchantlimit",
            name="max_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Maximum amount",
                max_digits=15,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="merchantlimit",
            name="max_deposit_decline_percent",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Max Deposit Decline %",
                max_digits=5,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="merchantlimit",
            name="max_operations",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Maximum number of operations",
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AlterField(
            model_name="merchantlimit",
            name="max_overall_decline_percent",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Max Overall Decline %",
                max_digits=5,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="merchantlimit",
            name="max_ratio",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Max Ratio %",
                max_digits=5,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="merchantlimit",
            name="max_withdrawal_decline_percent",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Max Withdrawal Decline %",
                max_digits=5,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="merchantlimit",
            name="min_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Minimum amount",
                max_digits=15,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="merchantlimit",
            name="period",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1h", "1 Hour"),
                    ("24h", "24 Hours"),
                    ("beginning_of_hour", "Beginning of Hour"),
                    ("beginning_of_day", "Beginning of Day"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="merchantlimit",
            name="total_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Total amount per period",
                max_digits=15,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
