# Generated by Django 5.1.3 on 2025-09-22 12:38

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("limits", "0002_customerlimit_notification_groups_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customerlimit",
            name="max_operation_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Maximum amount allowed for a single operation",
                max_digits=20,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                verbose_name="Maximum amount for a single operation",
            ),
        ),
        migrations.AlterField(
            model_name="customerlimit",
            name="min_operation_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Minimum amount allowed for a single operation",
                max_digits=20,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                verbose_name="Minimum amount for a single operation",
            ),
        ),
        migrations.AlterField(
            model_name="customerlimit",
            name="notification_groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="User groups that will receive notifications about this alert.",
                related_name="customer_limits_to_notify",
                to="auth.group",
            ),
        ),
        migrations.AlterField(
            model_name="customerlimit",
            name="slack_channel_override",
            field=models.CharField(
                blank=True,
                help_text="Override the default Slack channel for notifications.",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="merchantlimit",
            name="burst_minutes",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Number of minutes for checking operation bursts",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(60),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="merchantlimit",
            name="limit_type",
            field=models.CharField(
                choices=[
                    (
                        "max_successful_deposits",
                        "Maximum number of successful deposits per period",
                    ),
                    (
                        "max_overall_decline_percent",
                        "Maximum decline percentage per period",
                    ),
                    (
                        "max_withdrawal_decline_percent",
                        "Maximum withdrawal decline percentage per period",
                    ),
                    (
                        "max_deposit_decline_percent",
                        "Maximum deposit decline percentage per period",
                    ),
                    (
                        "min_amount_single_operation",
                        "Minimum amount for a single operation",
                    ),
                    (
                        "max_amount_single_operation",
                        "Maximum amount for a single operation",
                    ),
                    ("total_amount_deposits_period", "Total deposit amount per period"),
                    (
                        "total_amount_withdrawals_period",
                        "Total withdrawal amount per period",
                    ),
                    (
                        "max_withdrawal_to_deposit_ratio",
                        "Maximum withdrawal-to-deposit ratio per period",
                    ),
                    (
                        "max_operations_burst",
                        "Maximum number of any operations in a short period",
                    ),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="merchantlimit",
            name="notification_groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="User groups that will receive notifications about this alert.",
                related_name="merchant_limits_to_notify",
                to="auth.group",
            ),
        ),
        migrations.AlterField(
            model_name="merchantlimit",
            name="slack_channel_override",
            field=models.CharField(
                blank=True,
                help_text="Override the default Slack channel for notifications.",
                max_length=100,
                null=True,
            ),
        ),
    ]
