# Generated by Django 5.1.3 on 2025-12-01 10:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("limits", "0003_alter_customerlimit_max_operation_amount_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessCustomerLimit",
            fields=[],
            options={
                "verbose_name": "Business Customer Limit",
                "verbose_name_plural": "Business Customer Limits",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("limits.customerlimit",),
        ),
        migrations.CreateModel(
            name="BusinessMerchantLimit",
            fields=[],
            options={
                "verbose_name": "Business Merchant Limit",
                "verbose_name_plural": "Business Merchant Limits",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("limits.merchantlimit",),
        ),
        migrations.CreateModel(
            name="RiskCustomerLimit",
            fields=[],
            options={
                "verbose_name": "Risk Customer Limit",
                "verbose_name_plural": "Risk Customer Limits",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("limits.customerlimit",),
        ),
        migrations.CreateModel(
            name="RiskMerchantLimit",
            fields=[],
            options={
                "verbose_name": "Risk Merchant Limit",
                "verbose_name_plural": "Risk Merchant Limits",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("limits.merchantlimit",),
        ),
        migrations.AddField(
            model_name="customerlimit",
            name="category",
            field=models.CharField(
                choices=[("risk", "Risk"), ("business", "Business")],
                default="business",
                max_length=50,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="merchantlimit",
            name="category",
            field=models.CharField(
                choices=[("risk", "Risk"), ("business", "Business")],
                default="business",
                max_length=50,
            ),
            preserve_default=False,
        ),
    ]
