# Generated by Django 5.1.3 on 2025-12-01 10:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("limits", "0004_businesscustomerlimit_businessmerchantlimit_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GlobalRiskMerchantLimit",
            fields=[],
            options={
                "verbose_name": "Global Risk Merchant Limit",
                "verbose_name_plural": "Global Risk Merchant Limits",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("limits.merchantlimit",),
        ),
        migrations.AlterField(
            model_name="customerlimit",
            name="category",
            field=models.CharField(
                choices=[
                    ("risk", "Risk"),
                    ("global_risk", "Global Risk"),
                    ("business", "Business"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="merchantlimit",
            name="category",
            field=models.CharField(
                choices=[
                    ("risk", "Risk"),
                    ("global_risk", "Global Risk"),
                    ("business", "Business"),
                ],
                max_length=50,
            ),
        ),
    ]
