# Generated by Django 2.1.2 on 2019-02-11 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='datetime_calculated',
            field=models.DateTimeField(),
        ),
    ]
