# Generated by Django 4.0.5 on 2022-06-09 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0002_auto_20190211_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='data',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='rate',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
