"""
Django settings for rozert_pay project.

Generated by 'django-admin startproject' using Django 4.0.10.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

import logging
import os
import sys
import typing as ty
from os import getenv
from pathlib import Path

from django.utils.functional import cached_property
from dotenv import load_dotenv

from . import get_secrets_value

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
PROJECT_ROOT = BASE_DIR.parent
PROJECT_COMMON_ROOT = PROJECT_ROOT / "common"

PROJECT_COMMON_ROOT = BASE_DIR / "../common"
SHARED_APPS_DIR = BASE_DIR / "../shared-apps"

SILENCED_SYSTEM_CHECKS = ["models.E034"]

sys.path.append(str(SHARED_APPS_DIR))

from bm.logging import JsonFormatter, KeyValueFormatter  # noqa

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-haxf()&@o0jp&dmu-c9=q$bugrsm)ss(eel)1%mnq(zw@duvf$"

# SECURITY WARNING: don't run with debug turned on in production!
_DEBUG = os.environ.get("DEBUG", "True")
DEBUG = _DEBUG.lower() in ("true", "1", "yes", "t", "y")

DEBUG = False
ALLOWED_HOSTS: list[str] = ["*"]


AUTH_USER_MODEL = "account.User"

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django_extensions",
    "whitenoise",
    "rest_framework",
    "drf_spectacular",
    "webpack_loader",
    "django_object_actions",
    "django_json_widget",
    "django_celery_beat",
    "rangefilter",
    "auditlog",
    "rozert_pay.payment",
    "rozert_pay.account",
    "rozert_pay.limits",
    "rozert_pay.risk_lists",
    "rozert_pay.balances",
    "rozert_pay.payment_audit",
    "currency",
]

WEBPACK_LOADER = {
    "DEFAULT": {
        "CACHE": not DEBUG,
        "BUNDLE_DIR_NAME": "",
        "STATS_FILE": BASE_DIR / "front/build/webpack-stats.json",
    }
}

MIDDLEWARE = [
    "rozert_pay.common.middlewares.PrometheusMetricsMiddleware",  # MUST be first
    "bm.django_utils.middleware.RequestIdMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "rozert_pay.common.middlewares.LogResponseMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "auditlog.middleware.AuditlogMiddleware",
]

ROOT_URLCONF = "rozert_pay.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "rozert_pay/limits/templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "rozert_pay.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql_psycopg2",
        "NAME": os.environ.get("POSTGRES_DATABASE", "rozert_pay"),
        "USER": os.environ.get("POSTGRES_USER", "rozert_pay"),
        "PASSWORD": os.environ.get("POSTGRES_PASSWORD", "rozert_pay"),
        "HOST": os.environ.get("POSTGRES_HOST", "localhost"),
        "PORT": int(os.environ.get("POSTGRES_PORT", "5432")),
    },
}

REDIS_PASSWORD = get_secrets_value("REDIS_PASSWORD", getenv("REDIS_PASSWORD", ""))

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": f"redis://{os.environ.get('REDIS_HOST', 'localhost')}:6379/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "PASSWORD": REDIS_PASSWORD,
        },
    },
}

# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

STATICFILES_DIRS = [
    BASE_DIR / "front/build",
]

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


RABBITMQ_HOST = os.environ.get("RABBITMQ_HOST", "localhost")
RABBITMQ_USER = os.environ.get("RABBITMQ_USER", "guest")
RABBITMQ_PASSWORD = os.environ.get("RABBITMQ_PASSWORD", "guest")
CELERY_BROKER_URL = f"amqp://{RABBITMQ_USER}:{RABBITMQ_PASSWORD}@{RABBITMQ_HOST}:5672//"
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True


USE_JSON_LOGGING = os.environ.get("USE_JSON_LOGGING", False)


class PaymentAggregatorLogFormatter(logging.Formatter):
    def __init__(self) -> None:
        super().__init__()
        self.kv_formatter = KeyValueFormatter()
        self.json_formatter = JsonFormatter()

    @cached_property
    def use_json_logging(self) -> bool:
        from django.conf import settings

        return getattr(settings, "USE_JSON_LOGGING", False)

    def format(self, record):  # type: ignore[no-untyped-def]
        if self.use_json_logging:
            return self.json_formatter.format(record)
        return self.kv_formatter.format(record)


LOGGING: dict[str, ty.Any] = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "default": {
            "()": PaymentAggregatorLogFormatter,
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "default",
            "level": "NOTSET",
        },
    },
    "loggers": {
        "": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": True,
        },
        "django.request": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
    },
}

if getenv("DJANGO_QUERY_LOG"):
    LOGGING["loggers"]["django.db.backends"] = {
        "handlers": ["console"],
        "level": "DEBUG",
        "propagate": False,
    }


_IS_PRODUCTION = os.environ.get("IS_PRODUCTION", "False")
IS_PRODUCTION = _IS_PRODUCTION.lower() in ("true", "1", "yes", "t", "y")

# TODO: set prod keys
ENCRYPTION_KEYS = [
    "GPWfbDAWKP8zVXPoMD0m1bA5MPjXhuoSsRUM__9Qi8s=",
]

REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}


SPECTACULAR_SETTINGS = {
    "TITLE": "Rozert Pay",
    "DESCRIPTION": "Rozert Payment API",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
}

CSRF_TRUSTED_ORIGINS = [
    "https://ps-stage.rozert.cloud",
    "https://ps.rozert.cloud",
]

SENTRY_DSN = os.environ.get("SENTRY_DSN", None)

BACK_SECRET_KEY = get_secrets_value("BACK_SECRET_KEY", getenv("BACK_SECRET_KEY", ""))
SYSTEM_USER_EMAIL = getenv("SYSTEM_USER_EMAIL", "system@rozert.cloud")

EXTERNAL_ROZERT_HOST = "https://ps-stage.rozert.cloud"

IS_UNITTESTS = False

if IS_PRODUCTION:
    BETMASTER_BASE_URL = "https://main.bmhub.io/"
else:
    BETMASTER_BASE_URL = "https://admin.preprod.dev.betmaster.co/"

SLACK_TOKEN = os.environ.get("SLACK_TOKEN", None)
SLACK_UNEXPRECTED_NOTIFY_CHANNEL = "#tm-unexpected"

# TODO: ensure correct keys on prod!
ENCRYPTION_KEY_SET = {
    "pii": {
        "key_set_id": "pii",
        "primary_key_id": "default",
        "keys": [
            {
                "key_id": "default",
                "key_material": "39df0b4ad6dabc91facd3336faec452cec2507290010dda81ca7ac553b05c56e",
                "description": "default encryption key",
                "created_at": "2026-01-05 00:00:00",
                "status": "ENABLED",
            }
        ],
    },
    "pii_hash": {
        "key_set_id": "pii_hash",
        "primary_key_id": "default",
        "keys": [
            {
                "key_id": "default",
                "key_material": "39df0b4ad6dabc91facd3336faec452cec2507290010dda81ca7ac553b05c56e",
                "description": "default encryption key",
                "created_at": "2026-01-05 00:00:00",
                "status": "ENABLED",
            }
        ],
    },
    "credentials": {
        "key_set_id": "credentials",
        "primary_key_id": "default",
        "keys": [
            {
                "key_id": "default",
            }
        ],
    },
}

try:
    from .local_settings import *  # type: ignore[import-untyped] # noqa
except ImportError:
    pass


# Disable DRF Browsable API in non-debug environments
if not DEBUG:
    REST_FRAMEWORK["DEFAULT_RENDERER_CLASSES"] = (  # type: ignore[assignment]
        "rest_framework.renderers.JSONRenderer",
    )
