# Generated by Django 5.1.3 on 2025-09-04 18:47

import uuid
from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("payment", "0036_currencywallet_frozen_balance_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BalanceTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            (
                                "OPERATION_CONFIRMED",
                                "Successful deposit. Increases operational and pending balances.",
                            ),
                            (
                                "FEE",
                                "Fee charged for a service. Decreases operational balance.",
                            ),
                            (
                                "SETTLEMENT_REQUEST",
                                "Merchant requested a payout. Moves funds from available to frozen.",
                            ),
                            (
                                "SETTLEMENT_CANCEL",
                                "Payout request was cancelled. Moves funds from frozen back to available.",
                            ),
                            (
                                "SETTLEMENT_CONFIRMED",
                                "Payout was successfully processed. Decreases operational and frozen balances.",
                            ),
                            (
                                "SETTLEMENT_FROM_PROVIDER",
                                "Funds physically received from a payment provider. Decreases pending balance, making funds available.",
                            ),
                            (
                                "SETTLEMENT_REVERSAL",
                                "A previously successful payout was returned. Increases operational balance.",
                            ),
                            (
                                "CHARGEBACK",
                                "A chargeback was received. Decreases operational balance.",
                            ),
                            (
                                "ROLLING_RESERVE_HOLD",
                                "Funds held for rolling reserve. Moves funds from available to frozen.",
                            ),
                            (
                                "ROLLING_RESERVE_RELEASE",
                                "Rolling reserve period expired. Moves funds from frozen back to available.",
                            ),
                            (
                                "FROZEN",
                                "Manual freeze of funds by an operator. Moves funds from available to frozen.",
                            ),
                            (
                                "UNFROZEN",
                                "Manual unfreeze of funds by an operator. Moves funds from frozen back to available.",
                            ),
                            (
                                "MANUAL_ADJUSTMENT",
                                "Manual balance correction by an operator. Affects operational balance.",
                            ),
                            (
                                "INITIAL_MIGRATION",
                                "Initial balance state created during data migration.",
                            ),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "operational_before",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="The total funds (including pending and frozen) before the operation.",
                        max_digits=15,
                    ),
                ),
                (
                    "operational_after",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="The total funds after the operation.",
                        max_digits=15,
                    ),
                ),
                (
                    "frozen_before",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="The portion of operational funds that was frozen before the operation.",
                        max_digits=15,
                    ),
                ),
                (
                    "frozen_after",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="The portion of operational funds that is frozen after the operation.",
                        max_digits=15,
                    ),
                ),
                (
                    "pending_before",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="The portion of operational funds awaiting settlement before the operation.",
                        max_digits=15,
                    ),
                ),
                (
                    "pending_after",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="The portion of operational funds awaiting settlement after the operation.",
                        max_digits=15,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "initiator",
                    models.CharField(
                        choices=[
                            ("SYSTEM", "System"),
                            ("USER", "User"),
                            ("SERVICE", "Internal Service"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "currency_wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="balance_transactions",
                        to="payment.currencywallet",
                    ),
                ),
                (
                    "payment_transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="payment.paymenttransaction",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RollingReserveHold",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                ("hold_until", models.DateTimeField(db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("RELEASED", "Released")],
                        db_index=True,
                        default="ACTIVE",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "currency_wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rolling_reserve_holds",
                        to="payment.currencywallet",
                    ),
                ),
                (
                    "release_transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="released_rolling_reserve",
                        to="balances.balancetransaction",
                    ),
                ),
                (
                    "source_transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_rolling_reserve",
                        to="balances.balancetransaction",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
