apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: rozert-pay-api
  namespace: rozert-pay
spec:
  commonName: rozert-pay-api.dev.betmaster.co
  dnsNames:
  - rozert-pay-api.preprod.dev.betmaster.co
  - rozert-pay-api.dev.betmaster.co
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  privateKey:
    algorithm: ECDSA
    size: 256
  secretName: rozert-pay-api.dev.betmaster.co-tls
