# Generated by Django 5.1.3 on 2024-11-29 09:09

import django.contrib.postgres.fields
import django.db.models.deletion
import rozert_pay.common.encryption
import rozert_pay.payment.models
from django.conf import settings
from django.db import migrations, models
from rozert_pay.common.const import CeleryQueue


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CurrencyWallet",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("currency", models.CharField(max_length=3)),
                (
                    "balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "hold_balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PaymentSystem",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200, unique=True)),
                ("slug", models.CharField(max_length=200, null=True, unique=True)),
                (
                    "type",
                    models.CharField(
                        choices=[("spei_stp", "SPEI STP"), ("paycash", "PayCash")],
                        max_length=200,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "deposit_allowed_ttl_seconds",
                    models.PositiveIntegerField(
                        default=172800,
                        help_text="Time to live for deposit transactions. Initial transactions longer than this will be failed with decline code 'Too long execution'.",
                    ),
                ),
                (
                    "ip_whitelist",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=50),
                        default=list,
                        size=None,
                    ),
                ),
                ("client_request_timeout", models.FloatField(default=30)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MerchantGroup",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200, unique=True)),
                (
                    "queue",
                    models.CharField(
                        choices=CeleryQueue.choices,
                        default="normal",
                        max_length=200,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Merchant",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200, unique=True)),
                ("secret_key", models.CharField(max_length=200, unique=True)),
                ("sandbox", models.BooleanField(default=False)),
                (
                    "login_users",
                    models.ManyToManyField(
                        help_text="Users, who can login to this merchant's dashboard",
                        related_name="merchants",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "merchant_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="payment.merchantgroup",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PaymentTransaction",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "type",
                    models.CharField(
                        choices=[("deposit", "Deposit"), ("withdrawal", "Withdrawal")],
                        max_length=20,
                    ),
                ),
                ("currency", models.CharField(max_length=3)),
                ("callback_url", models.URLField(blank=True, null=True)),
                (
                    "customer_id",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "deposit_account",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "id_in_payment_system",
                    models.CharField(
                        blank=True, db_index=True, max_length=200, null=True
                    ),
                ),
                (
                    "decline_code",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "decline_reason",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("instruction", models.JSONField(blank=True, null=True)),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="payment.currencywallet",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OutcomingCallback",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "callback_type",
                    models.CharField(
                        choices=[
                            ("deposit_account_created", "Deposit Account Created"),
                            ("deposit_received", "Deposit Received"),
                            ("transaction_updated", "Transaction Updated"),
                        ],
                        max_length=255,
                    ),
                ),
                ("target", models.URLField()),
                ("body", models.JSONField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("pending", "Pending"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error", models.TextField(blank=True, null=True)),
                ("last_attempt_at", models.DateTimeField(blank=True, null=True)),
                ("max_attempts", models.PositiveIntegerField(default=10)),
                ("current_attempt", models.PositiveIntegerField(default=0)),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="payment.paymenttransaction",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="IncomingCallback",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("body", models.TextField()),
                ("get_params", models.JSONField()),
                ("ip", models.GenericIPAddressField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("pending", "Pending"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error", models.TextField(blank=True, null=True)),
                ("traceback", models.TextField(blank=True, null=True)),
                (
                    "remote_transaction_status",
                    models.JSONField(
                        default=dict,
                        encoder=rozert_pay.payment.models.CustomJsonEncoder,
                    ),
                ),
                (
                    "system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="payment.paymentsystem",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="payment.paymenttransaction",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PaymentTransactionEventLog",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("error", "Error"),
                            ("callback_sending_attempt", "Callback Sending Attempt"),
                            ("external_api_request", "External API Request"),
                            ("important", "!!! Important !!!"),
                        ],
                        max_length=255,
                    ),
                ),
                ("extra", models.JSONField(default=dict)),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="payment.paymenttransaction",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Wallet",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("credentials", rozert_pay.common.encryption.EncryptedField()),
                ("default_callback_url", models.URLField(blank=True, null=True)),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="payment.merchant",
                    ),
                ),
                (
                    "system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="payment.paymentsystem",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="currencywallet",
            name="wallet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="payment.wallet"
            ),
        ),
        migrations.CreateModel(
            name="ACLGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("all_groups", models.BooleanField(default=False)),
                ("all_wallets", models.BooleanField(default=False)),
                ("all_users", models.BooleanField(default=False)),
                ("all_systems", models.BooleanField(default=False)),
                (
                    "level",
                    models.CharField(
                        choices=[("read", "Read"), ("write", "Write")],
                        default="read",
                        max_length=20,
                    ),
                ),
                ("users", models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ("groups", models.ManyToManyField(to="payment.merchantgroup")),
                ("systems", models.ManyToManyField(to="payment.paymentsystem")),
                ("wallets", models.ManyToManyField(to="payment.wallet")),
            ],
        ),
        migrations.CreateModel(
            name="DepositAccount",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("customer_id", models.CharField(max_length=100)),
                ("unique_account_identifier", models.CharField(max_length=100)),
                ("extra", models.JSONField(blank=True, default=dict)),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="payment.wallet"
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("wallet", "customer_id"),
                        name="unique_customer_id_per_merchant",
                    ),
                    models.UniqueConstraint(
                        fields=("wallet", "unique_account_identifier"),
                        name="unique_account_identifier",
                    ),
                ],
            },
        ),
        migrations.AlterUniqueTogether(
            name="currencywallet",
            unique_together={("wallet", "currency")},
        ),
    ]
