# Generated by Django 5.1.3 on 2024-11-29 09:37

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0002_merchant_uuid_paymenttransaction_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallet",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
