# Generated by Django 5.1.3 on 2024-11-29 10:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0003_wallet_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallet",
            name="name",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
    ]
