# Generated by Django 5.1.3 on 2024-11-29 10:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0004_wallet_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="outcomingcallback",
            name="logs",
            field=models.TextField(blank=True, null=True),
        ),
    ]
