# Generated by Django 5.1.3 on 2024-12-03 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0005_outcomingcallback_logs"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymenttransactioneventlog",
            name="incoming_callback",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="payment.incomingcallback",
            ),
        ),
    ]
