# Generated by Django 5.1.3 on 2024-12-03 14:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0006_paymenttransactioneventlog_incoming_callback"),
    ]

    operations = [
        migrations.AddField(
            model_name="incomingcallback",
            name="error_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ip_not_whitelisted", "IP not whitelisted"),
                    ("invalid_signature", "Invalid signature"),
                    ("parsing_error", "Parsing error"),
                    ("validation_error", "Validation error"),
                    ("unknown_error", "Unknown error"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="incomingcallback",
            name="get_params",
            field=models.JSONField(blank=True),
        ),
    ]
