# Generated by Django 5.1.3 on 2024-12-05 16:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0007_incomingcallback_error_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymenttransaction",
            name="extra",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
