# Generated by Django 5.1.3 on 2024-12-05 16:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0008_paymenttransaction_extra"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymenttransaction",
            name="extra",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
