# Generated by Django 5.1.3 on 2024-12-13 07:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0009_alter_paymenttransaction_extra"),
    ]

    operations = [
        migrations.AddField(
            model_name="incomingcallback",
            name="headers",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
