# Generated by Django 5.1.3 on 2024-12-13 07:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0010_incomingcallback_headers"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentsystem",
            name="callback_secret_key",
            field=models.CharField(
                blank=True,
                help_text="Secret key for callbacks from payment system",
                max_length=200,
                null=True,
            ),
        ),
    ]
