# Generated by Django 5.1.3 on 2024-12-23 12:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0011_paymentsystem_callback_secret_key"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="paymenttransaction",
            options={
                "permissions": [
                    ("can_actualize_transaction", "Can actualize payment transaction"),
                    ("can_set_transaction_status", "Can set transaction status"),
                ]
            },
        ),
        migrations.AddField(
            model_name="paymenttransactioneventlog",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="incomingcallback",
            name="error_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ip_not_whitelisted", "IP not whitelisted"),
                    ("invalid_signature", "Invalid signature"),
                    ("parsing_error", "Parsing error"),
                    ("validation_error", "Validation error"),
                    ("unknown_error", "Unknown error"),
                    ("authorization_error", "Authorization error"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="paymentsystem",
            name="ip_whitelist",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=50),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="paymenttransactioneventlog",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("error", "Error"),
                    ("callback_sending_attempt", "Callback Sending Attempt"),
                    ("external_api_request", "External API Request"),
                    ("important", "!!! Important !!!"),
                    ("transaction_actualization", "Transaction Actualization (Admin)"),
                    ("transaction_set_status", "Transaction Set Status (Admin)"),
                ],
                max_length=255,
            ),
        ),
    ]
