# Generated by Django 5.1.3 on 2025-02-13 10:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0012_alter_paymenttransaction_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymenttransaction",
            name="check_status_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="paymenttransaction",
            name="redirect_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="paymenttransactioneventlog",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("error", "Error"),
                    ("callback_sending_attempt", "Callback Sending Attempt"),
                    ("external_api_request", "External API Request"),
                    ("callback_retry_requested", "Callback Retry Requested"),
                    ("important", "!!! Important !!!"),
                    ("transaction_actualization", "Transaction Actualization (Admin)"),
                    ("transaction_set_status", "Transaction Set Status (Admin)"),
                    (
                        "withdrawal_stuck_in_processing",
                        "Withdrawal Stuck in Processing",
                    ),
                ],
                max_length=255,
            ),
        ),
    ]
