# Generated by Django 5.1.3 on 2025-02-17 16:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0013_paymenttransaction_check_status_until_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentsystem",
            name="type",
            field=models.CharField(
                choices=[
                    ("spei_stp", "SPEI STP"),
                    ("stp_codi", "STP CODI"),
                    ("paycash", "PayCash"),
                ],
                max_length=200,
            ),
        ),
    ]
