# Generated by Django 5.1.3 on 2025-02-13 16:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0013_paymenttransaction_check_status_until_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymenttransaction",
            name="external_account_id",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="paymentsystem",
            name="type",
            field=models.CharField(
                choices=[
                    ("spei_stp", "SPEI STP"),
                    ("paycash", "PayCash"),
                    ("paypal", "PayPal"),
                ],
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="paymenttransaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("success", "Success"),
                    ("failed", "Failed"),
                    ("refunded", "Refunded"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
