# Generated by Django 5.1.3 on 2025-03-03 13:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0014_alter_paymentsystem_type"),
        ("payment", "0014_paymenttransaction_external_account_id_and_more"),
    ]

    operations = []
