# Generated by Django 5.1.3 on 2025-03-03 13:50

import bm.utils
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0015_merge_20250303_1340"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentsystem",
            name="withdrawal_allowed_ttl_seconds",
            field=models.PositiveIntegerField(
                default=86400,
                help_text="Time to live for withdrawal transactions. Initial transactions longer than this will be failed with decline code 'Too long execution'.",
            ),
        ),
        migrations.AlterField(
            model_name="paymentsystem",
            name="type",
            field=models.CharField(
                choices=[
                    ("spei_stp", "SPEI STP"),
                    ("stp_codi", "STP CODI"),
                    ("paycash", "PayCash"),
                    ("paypal", "PayPal"),
                ],
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="paymenttransactioneventlog",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("error", "Error"),
                    ("callback_sending_attempt", "Callback Sending Attempt"),
                    ("external_api_request", "External API Request"),
                    ("callback_retry_requested", "Callback Retry Requested"),
                    ("important", "!!! Important !!!"),
                    ("transaction_actualization", "Transaction Actualization (Admin)"),
                    ("transaction_set_status", "Transaction Set Status (Admin)"),
                    (
                        "withdrawal_stuck_in_processing",
                        "Withdrawal Stuck in Processing",
                    ),
                    ("info", "Info"),
                ],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="paymenttransactioneventlog",
            name="extra",
            field=models.JSONField(default=dict, encoder=bm.utils.BMJsonEncoder),
        ),
    ]
