# Generated by Django 5.1.3 on 2025-03-17 14:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0014_paymenttransaction_external_account_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallet",
            name="comment",
            field=models.TextField(blank=True, default=""),
        ),
    ]
