# Generated by Django 5.1.3 on 2025-03-17 15:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0017_wallet_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallet",
            name="logs",
            field=models.TextField(blank=True, default=""),
        ),
    ]
