# Generated by Django 5.1.7 on 2025-03-18 10:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0016_paymentsystem_withdrawal_allowed_ttl_seconds_and_more"),
        ("payment", "0018_wallet_logs"),
    ]

    operations = []
