# Generated by Django 5.1.7 on 2025-03-20 10:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0019_merge_20250318_1026"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallet",
            name="sandbox_finalization_delay_seconds",
            field=models.PositiveIntegerField(default=60),
        ),
    ]
