# Generated by Django 5.1.7 on 2025-03-25 09:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0019_merge_20250318_1026"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentsystem",
            name="ip_whitelist_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="paymenttransactioneventlog",
            name="request_id",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
