# Generated by Django 5.1.7 on 2025-03-25 13:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0020_paymentsystem_ip_whitelist_enabled_and_more"),
        ("payment", "0020_wallet_sandbox_finalization_delay_seconds"),
    ]

    operations = []
