# SAFE MIGRATION
# Generated by Django 5.1.3 on 2025-05-19 09:52

import uuid

import django.db.models.deletion
import rozert_pay.common.encryption
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0021_merge_20250325_1331"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("uuid", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("external_id", models.CharField(max_length=255, unique=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("language", models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                "abstract": False,
                "ordering": ("id",),
            },
        ),
        migrations.RemoveField(
            model_name="paymenttransaction",
            name="customer_id",
        ),
        migrations.RemoveField(
            model_name="paymenttransaction",
            name="deposit_account",
        ),
        migrations.AlterField(
            model_name="paymentsystem",
            name="type",
            field=models.CharField(
                choices=[
                    ("spei_stp", "SPEI STP"),
                    ("stp_codi", "STP CODI"),
                    ("d24_mercadopago", "D24 MercadoPago"),
                    ("paycash", "PayCash"),
                    ("paypal", "PayPal"),
                    ("appex", "Appex"),
                    ("conekta_oxxo", "Conekta OXXO"),
                ],
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="paymenttransaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("success", "Success"),
                    ("failed", "Failed"),
                    ("refunded", "Refunded"),
                    ("charged_back", "Charged Back"),
                    ("charged_back_reversal", "Charged Back Reversal"),
                ],
                default="pending",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="paymenttransactioneventlog",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("error", "Error"),
                    ("callback_sending_attempt", "Callback Sending Attempt"),
                    ("external_api_request", "External API Request"),
                    ("callback_retry_requested", "Callback Retry Requested"),
                    ("important", "!!! Important !!!"),
                    ("transaction_actualization", "Transaction Actualization (Admin)"),
                    ("transaction_set_status", "Transaction Set Status (Admin)"),
                    (
                        "withdrawal_stuck_in_processing",
                        "Withdrawal Stuck in Processing",
                    ),
                    ("info", "Info"),
                    ("customer_redirect_received", "Customer Redirect Received"),
                    ("charge_back", "Charge Back"),
                    ("charge_back_reversal", "Charge Back Reversal"),
                ],
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="paymenttransaction",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="payment.customer",
            ),
        ),
        migrations.CreateModel(
            name="CustomerCard",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("uuid", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("unique_identity", models.CharField(max_length=200)),
                ("card_data", rozert_pay.common.encryption.EncryptedField()),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="payment.customer",
                    ),
                ),
            ],
            options={
                "unique_together": {("unique_identity", "customer")},
            },
        ),
        migrations.AddField(
            model_name="paymenttransaction",
            name="customer_card",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="payment.customercard",
            ),
        ),
    ]
