# Generated by Django 5.1.3 on 2025-06-06 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0022_customer_remove_paymenttransaction_customer_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StpCodiUniqueIds",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "transaction",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="payment.paymenttransaction",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
