# Generated by Django 5.1.3 on 2025-06-09 15:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0023_eventlog_customer_extra_customer_phone_and_more"),
        ("payment", "0023_stpcodiuniqueids"),
    ]

    operations = []
