# Generated by Django 5.1.3 on 2025-06-04 15:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0023_eventlog_customer_extra_customer_phone_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymenttransaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("success", "Success"),
                    ("failed", "Failed"),
                    ("charged_back", "Charged Back"),
                    ("charged_back_reversal", "Charged Back Reversal"),
                ],
                default="pending",
                max_length=255,
            ),
        ),
    ]
