# Generated by Django 5.1.3 on 2025-06-09 10:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0024_alter_paymenttransaction_status"),
        ("payment", "0024_merge_20250606_1543"),
    ]

    operations = []
