# Generated by Django 5.1.3 on 2025-06-11 09:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0024_merge_20250609_1515"),
        ("payment", "0025_merge_20250609_1030"),
    ]

    operations = []
