# Generated by Django 5.1.3 on 2025-07-21 12:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0026_merge_20250611_0940"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customerdepositinstruction",
            name="system_type",
            field=models.CharField(
                choices=[
                    ("spei_stp", "SPEI STP"),
                    ("stp_codi", "STP CODI"),
                    ("d24_mercadopago", "D24 MercadoPago"),
                    ("paycash", "PayCash"),
                    ("paypal", "PayPal"),
                    ("bitso_spei", "Bitso SPEI"),
                    ("appex", "Appex"),
                    ("conekta_oxxo", "Conekta OXXO"),
                    ("cardpay_bankcard", "Cardpay Bankcard"),
                ],
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="customerexternalpaymentsystemaccount",
            name="system_type",
            field=models.CharField(
                choices=[
                    ("spei_stp", "SPEI STP"),
                    ("stp_codi", "STP CODI"),
                    ("d24_mercadopago", "D24 MercadoPago"),
                    ("paycash", "PayCash"),
                    ("paypal", "PayPal"),
                    ("bitso_spei", "Bitso SPEI"),
                    ("appex", "Appex"),
                    ("conekta_oxxo", "Conekta OXXO"),
                    ("cardpay_bankcard", "Cardpay Bankcard"),
                ],
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="eventlog",
            name="system_type",
            field=models.CharField(
                choices=[
                    ("spei_stp", "SPEI STP"),
                    ("stp_codi", "STP CODI"),
                    ("d24_mercadopago", "D24 MercadoPago"),
                    ("paycash", "PayCash"),
                    ("paypal", "PayPal"),
                    ("bitso_spei", "Bitso SPEI"),
                    ("appex", "Appex"),
                    ("conekta_oxxo", "Conekta OXXO"),
                    ("cardpay_bankcard", "Cardpay Bankcard"),
                ],
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="paymentsystem",
            name="type",
            field=models.CharField(
                choices=[
                    ("spei_stp", "SPEI STP"),
                    ("stp_codi", "STP CODI"),
                    ("d24_mercadopago", "D24 MercadoPago"),
                    ("paycash", "PayCash"),
                    ("paypal", "PayPal"),
                    ("bitso_spei", "Bitso SPEI"),
                    ("appex", "Appex"),
                    ("conekta_oxxo", "Conekta OXXO"),
                    ("cardpay_bankcard", "Cardpay Bankcard"),
                ],
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="paymenttransaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("success", "Success"),
                    ("failed", "Failed"),
                    ("refunded", "Refunded"),
                    ("charged_back", "Charged Back"),
                    ("charged_back_reversal", "Charged Back Reversal"),
                ],
                default="pending",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="paymenttransaction",
            name="system_type",
            field=models.CharField(
                choices=[
                    ("spei_stp", "SPEI STP"),
                    ("stp_codi", "STP CODI"),
                    ("d24_mercadopago", "D24 MercadoPago"),
                    ("paycash", "PayCash"),
                    ("paypal", "PayPal"),
                    ("bitso_spei", "Bitso SPEI"),
                    ("appex", "Appex"),
                    ("conekta_oxxo", "Conekta OXXO"),
                    ("cardpay_bankcard", "Cardpay Bankcard"),
                ],
                max_length=200,
            ),
        ),
    ]
