# Generated by Django 5.1.3 on 2025-07-08 09:22

import django.db.models.deletion
import rozert_pay.payment.models
from bm import payment as shared_payment_const
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0026_merge_20250611_0940"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bank",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=300)),
                (
                    "is_non_bank",
                    models.BooleanField(
                        default=False,
                        verbose_name="Other licensed financial institution",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bank",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="PaymentCardBank",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "bin",
                    models.IntegerField(
                        unique=True,
                        validators=[rozert_pay.payment.models.validate_bin],
                        verbose_name="BIN",
                    ),
                ),
                (
                    "card_type",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Unknown"),
                            (1, "Visa"),
                            (2, "MasterCard"),
                            (3, "Maestro"),
                            (4, "China UnionPay"),
                            (5, "Mir"),
                            (6, "American Express"),
                            (7, "Dankort"),
                            (8, "DinaCard"),
                            (9, "Diners Club International"),
                            (10, "Discover"),
                            (11, "JCB"),
                            (12, "VPay"),
                        ],
                        default=0,
                    ),
                ),
                (
                    "card_class",
                    models.TextField(
                        choices=[
                            ("credit", "Credit"),
                            ("debit", "Debit"),
                            ("charge", "Charge"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "is_virtual",
                    models.BooleanField(default=False, verbose_name="Virtual Card"),
                ),
                (
                    "is_prepaid",
                    models.BooleanField(default=False, verbose_name="Prepaid Card"),
                ),
                (
                    "raw_category",
                    models.TextField(
                        blank=True,
                        help_text="Raw from XML file",
                        null=True,
                        verbose_name="Raw Category",
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        choices=shared_payment_const.COUNTRY_CHOICES,
                        max_length=10,
                    ),
                ),
                ("remark", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bank",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bins",
                        to="payment.bank",
                    ),
                ),
            ],
            options={
                "verbose_name": "BIN",
                "ordering": ("bin",),
            },
        ),
        migrations.CreateModel(
            name="BitsoSpeiCardBank",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "code",
                    models.CharField(
                        max_length=10, unique=True, verbose_name="Bank Code"
                    ),
                ),
                ("name", models.CharField(max_length=300, verbose_name="Bank Name")),
                (
                    "country_code",
                    models.CharField(
                        choices=shared_payment_const.COUNTRY_CHOICES,
                        max_length=2,
                        verbose_name="Country Code",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "banks",
                    models.ManyToManyField(
                        blank=True,
                        related_name="bitso_banks",
                        to="payment.paymentcardbank",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bitso SPEI Bank",
                "verbose_name_plural": "Bitso SPEI Banks",
                "ordering": ("code",),
            },
        ),
    ]
