# Generated by Django 5.1.3 on 2025-07-22 11:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0027_bank_paymentcardbank_bitsospeicardbank"),
        ("payment", "0028_alter_customerdepositinstruction_system_type_and_more"),
    ]

    operations = []
