# Generated by Django 5.1.3 on 2025-07-22 14:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0028_alter_customerdepositinstruction_system_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallet",
            name="allow_negative_balances",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="customerdepositinstruction",
            name="system_type",
            field=models.CharField(
                choices=[
                    ("spei_stp", "SPEI STP"),
                    ("stp_codi", "STP CODI"),
                    ("d24_mercadopago", "D24 MercadoPago"),
                    ("paycash", "PayCash"),
                    ("paypal", "PayPal"),
                    ("bitso_spei", "Bitso SPEI"),
                    ("appex", "Appex"),
                    ("conekta_oxxo", "Conekta OXXO"),
                    ("cardpay_cards", "Cardpay Cards"),
                ],
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="customerexternalpaymentsystemaccount",
            name="system_type",
            field=models.CharField(
                choices=[
                    ("spei_stp", "SPEI STP"),
                    ("stp_codi", "STP CODI"),
                    ("d24_mercadopago", "D24 MercadoPago"),
                    ("paycash", "PayCash"),
                    ("paypal", "PayPal"),
                    ("bitso_spei", "Bitso SPEI"),
                    ("appex", "Appex"),
                    ("conekta_oxxo", "Conekta OXXO"),
                    ("cardpay_cards", "Cardpay Cards"),
                ],
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="eventlog",
            name="system_type",
            field=models.CharField(
                choices=[
                    ("spei_stp", "SPEI STP"),
                    ("stp_codi", "STP CODI"),
                    ("d24_mercadopago", "D24 MercadoPago"),
                    ("paycash", "PayCash"),
                    ("paypal", "PayPal"),
                    ("bitso_spei", "Bitso SPEI"),
                    ("appex", "Appex"),
                    ("conekta_oxxo", "Conekta OXXO"),
                    ("cardpay_cards", "Cardpay Cards"),
                ],
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="paymentsystem",
            name="type",
            field=models.CharField(
                choices=[
                    ("spei_stp", "SPEI STP"),
                    ("stp_codi", "STP CODI"),
                    ("d24_mercadopago", "D24 MercadoPago"),
                    ("paycash", "PayCash"),
                    ("paypal", "PayPal"),
                    ("bitso_spei", "Bitso SPEI"),
                    ("appex", "Appex"),
                    ("conekta_oxxo", "Conekta OXXO"),
                    ("cardpay_cards", "Cardpay Cards"),
                ],
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="paymenttransaction",
            name="system_type",
            field=models.CharField(
                choices=[
                    ("spei_stp", "SPEI STP"),
                    ("stp_codi", "STP CODI"),
                    ("d24_mercadopago", "D24 MercadoPago"),
                    ("paycash", "PayCash"),
                    ("paypal", "PayPal"),
                    ("bitso_spei", "Bitso SPEI"),
                    ("appex", "Appex"),
                    ("conekta_oxxo", "Conekta OXXO"),
                    ("cardpay_cards", "Cardpay Cards"),
                ],
                max_length=200,
            ),
        ),
    ]
