# Generated by Django 5.1.3 on 2025-07-25 09:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0029_merge_20250722_1153"),
        ("payment", "0030_wallet_allow_negative_balances_and_more"),
    ]

    operations = []
