# Generated by Django 5.1.3 on 2025-08-06 13:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0031_merge_20250725_0945"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentsystem",
            name="slug",
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
