# Generated by Django 5.1.3 on 2025-08-07 13:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0031_merge_20250725_0945"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customerdepositinstruction",
            name="system_type",
            field=models.CharField(
                choices=[
                    ("spei_stp", "SPEI STP"),
                    ("stp_codi", "STP CODI"),
                    ("d24_mercadopago", "D24 MercadoPago"),
                    ("paycash", "PayCash"),
                    ("paypal", "PayPal"),
                    ("bitso_spei", "Bitso SPEI"),
                    ("appex", "Appex"),
                    ("conekta_oxxo", "Conekta OXXO"),
                    ("cardpay_cards", "Cardpay Cards"),
                    ("cardpay_applepay", "Cardpay Applepay"),
                ],
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="customerexternalpaymentsystemaccount",
            name="system_type",
            field=models.CharField(
                choices=[
                    ("spei_stp", "SPEI STP"),
                    ("stp_codi", "STP CODI"),
                    ("d24_mercadopago", "D24 MercadoPago"),
                    ("paycash", "PayCash"),
                    ("paypal", "PayPal"),
                    ("bitso_spei", "Bitso SPEI"),
                    ("appex", "Appex"),
                    ("conekta_oxxo", "Conekta OXXO"),
                    ("cardpay_cards", "Cardpay Cards"),
                    ("cardpay_applepay", "Cardpay Applepay"),
                ],
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="eventlog",
            name="system_type",
            field=models.CharField(
                choices=[
                    ("spei_stp", "SPEI STP"),
                    ("stp_codi", "STP CODI"),
                    ("d24_mercadopago", "D24 MercadoPago"),
                    ("paycash", "PayCash"),
                    ("paypal", "PayPal"),
                    ("bitso_spei", "Bitso SPEI"),
                    ("appex", "Appex"),
                    ("conekta_oxxo", "Conekta OXXO"),
                    ("cardpay_cards", "Cardpay Cards"),
                    ("cardpay_applepay", "Cardpay Applepay"),
                ],
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="paymentsystem",
            name="slug",
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="paymentsystem",
            name="type",
            field=models.CharField(
                choices=[
                    ("spei_stp", "SPEI STP"),
                    ("stp_codi", "STP CODI"),
                    ("d24_mercadopago", "D24 MercadoPago"),
                    ("paycash", "PayCash"),
                    ("paypal", "PayPal"),
                    ("bitso_spei", "Bitso SPEI"),
                    ("appex", "Appex"),
                    ("conekta_oxxo", "Conekta OXXO"),
                    ("cardpay_cards", "Cardpay Cards"),
                    ("cardpay_applepay", "Cardpay Applepay"),
                ],
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="paymenttransaction",
            name="system_type",
            field=models.CharField(
                choices=[
                    ("spei_stp", "SPEI STP"),
                    ("stp_codi", "STP CODI"),
                    ("d24_mercadopago", "D24 MercadoPago"),
                    ("paycash", "PayCash"),
                    ("paypal", "PayPal"),
                    ("bitso_spei", "Bitso SPEI"),
                    ("appex", "Appex"),
                    ("conekta_oxxo", "Conekta OXXO"),
                    ("cardpay_cards", "Cardpay Cards"),
                    ("cardpay_applepay", "Cardpay Applepay"),
                ],
                max_length=200,
            ),
        ),
    ]
