# Generated by Django 5.2.5 on 2025-08-13 15:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0032_alter_customerdepositinstruction_system_type_and_more"),
        ("payment", "0032_alter_paymentsystem_slug"),
    ]

    operations = []
