# Generated by Django 5.1.3 on 2025-08-29 13:36

from django.db import migrations, models
from rozert_pay.common.const import CeleryQueue, PaymentSystemType


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0033_merge_20250813_1509"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customerdepositinstruction",
            name="system_type",
            field=models.CharField(
                choices=PaymentSystemType.choices,
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="customerexternalpaymentsystemaccount",
            name="system_type",
            field=models.CharField(
                choices=PaymentSystemType.choices,
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="eventlog",
            name="system_type",
            field=models.CharField(
                choices=PaymentSystemType.choices,
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="merchantgroup",
            name="queue",
            field=models.CharField(
                choices=CeleryQueue.choices,
                default="normal",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="paymentsystem",
            name="type",
            field=models.CharField(
                choices=PaymentSystemType.choices,
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="paymenttransaction",
            name="system_type",
            field=models.CharField(
                choices=PaymentSystemType.choices,
                max_length=200,
            ),
        ),
    ]
