# Generated by Django 5.1.3 on 2025-09-03 10:56

from django.db import migrations, models
from rozert_pay.common.const import EventType


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0034_alter_customerdepositinstruction_system_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventlog",
            name="event_type",
            field=models.CharField(
                choices=EventType.choices,
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="paymenttransactioneventlog",
            name="event_type",
            field=models.CharField(
                choices=EventType.choices,
                max_length=255,
            ),
        ),
    ]
