# Generated by Django 5.1.3 on 2025-11-12 13:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0035_alter_eventlog_event_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="currencywallet",
            name="frozen_balance",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Part of operational_balance that is temporarily locked.",
                max_digits=15,
            ),
        ),
        migrations.AddField(
            model_name="currencywallet",
            name="operational_balance",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Total funds, including confirmed and pending.",
                max_digits=15,
            ),
        ),
        migrations.AddField(
            model_name="currencywallet",
            name="pending_balance",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Part of operational_balance that is awaiting settlement from a provider.",
                max_digits=15,
            ),
        ),
    ]
