# Generated by Django 5.1.3 on 2025-12-09 13:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0037_customer_risk_control_merchant_risk_control_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TransactionManager",
            fields=[],
            options={
                "verbose_name": "Transaction Manager",
                "verbose_name_plural": "Transaction Manager",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("payment.paymenttransaction",),
        ),
    ]
