# Generated by Django 5.1.3 on 2026-01-05 13:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0037_customer_risk_control_merchant_risk_control_and_more"),
        ("payment", "0037_paymenttransaction_bitso_spei_lookup_index"),
    ]

    operations = []
