# Generated by Django 5.1.3 on 2025-12-23 08:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0037_paymenttransaction_bitso_spei_lookup_index"),
        ("payment", "0038_transactionmanager"),
    ]

    operations = []
