# Generated by Django 5.1.3 on 2026-01-09 11:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0038_merge_20260105_1357"),
        ("payment", "0039_merge_20251223_0833"),
    ]

    operations = []
