# Generated by Django 5.1.3 on 2026-01-09 11:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0040_merge_20260109_1120"),
    ]

    operations = [
        migrations.CreateModel(
            name="MuweSpeiBank",
            fields=[
                (
                    "code",
                    models.CharField(
                        help_text="Bank code (e.g., '40014' for Santander)",
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Bank name (e.g., 'SANTANDER')", max_length=200
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this bank is currently supported by MUWE",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "MUWE SPEI Bank",
                "verbose_name_plural": "MUWE SPEI Banks",
                "db_table": "payment_muwe_spei_bank",
                "ordering": ["name"],
            },
        ),
    ]
