# Generated by Django 5.1.3 on 2026-01-20 12:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0041_alter_customer_email_rename_email_customer__email_and_more"),
        ("payment", "0041_muwespeibank"),
    ]

    operations = []
