# Generated by Django 5.1.3 on 2026-02-02

from django.db import migrations
from rozert_pay.common import const

FLAG_NAME = const.CARDPAY_APPLEPAY_BANKCARD_FLAG


def add_flag(apps, schema_editor) -> None:
    Flag = apps.get_model("waffle", "Flag")
    Flag.objects.get_or_create(
        name=FLAG_NAME,
        defaults={
            "everyone": False,
        },
    )


def remove_flag(apps, schema_editor) -> None:
    Flag = apps.get_model("waffle", "Flag")
    Flag.objects.filter(name=FLAG_NAME).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0042_merge_20260120_1259"),
        ("waffle", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(add_flag, remove_flag),
    ]
