# Generated by Django 5.1.3 on 2026-02-12 09:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0045_remove_customer_legacy_fields"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="paymenttransaction",
            options={
                "permissions": [
                    ("can_actualize_transaction", "Can actualize payment transaction"),
                    (
                        "can_set_transaction_status",
                        "Can set transaction status (custom)",
                    ),
                ]
            },
        ),
    ]
