#!/usr/bin/env bash
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT/rozert-pay"

if [[ -f .env ]]; then
  set -a
  source .env
  set +a
fi

DB_NAME="${POSTGRES_DB:-rozert_pay}"
DB_PORT="${POSTGRES_PORT:-5432}"
DB_HOST="${POSTGRES_HOST:-localhost}"
READONLY_USER="${CODEX_READONLY_USER:-codex_readonly}"
READONLY_PASSWORD="${CODEX_READONLY_PASSWORD:-codex_readonly}"

USE_DOCKER="${USE_DOCKER:-0}"
if [[ "$USE_DOCKER" == "0" ]] && ! getent passwd postgres &>/dev/null; then
  USE_DOCKER=1
fi

if [[ "$USE_DOCKER" == "1" ]]; then
  SUPERUSER="${POSTGRES_USER:-postgres}"
  docker compose exec -T db psql -U "$SUPERUSER" -d "$DB_NAME" <<SQL
DO \$\$
BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '$READONLY_USER') THEN
    EXECUTE format('CREATE USER %I WITH PASSWORD %L', '$READONLY_USER', '$READONLY_PASSWORD');
  ELSE
    EXECUTE format('ALTER USER %I WITH PASSWORD %L', '$READONLY_USER', '$READONLY_PASSWORD');
  END IF;
END
\$\$;
GRANT CONNECT ON DATABASE $DB_NAME TO $READONLY_USER;
\c $DB_NAME
GRANT USAGE ON SCHEMA public TO $READONLY_USER;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO $READONLY_USER;
GRANT SELECT ON ALL SEQUENCES IN SCHEMA public TO $READONLY_USER;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO $READONLY_USER;
SQL
else
  sudo -u postgres psql -d "$DB_NAME" <<SQL
DO \$\$
BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '$READONLY_USER') THEN
    EXECUTE format('CREATE USER %I WITH PASSWORD %L', '$READONLY_USER', '$READONLY_PASSWORD');
  ELSE
    EXECUTE format('ALTER USER %I WITH PASSWORD %L', '$READONLY_USER', '$READONLY_PASSWORD');
  END IF;
END
\$\$;
GRANT CONNECT ON DATABASE $DB_NAME TO $READONLY_USER;
\c $DB_NAME
GRANT USAGE ON SCHEMA public TO $READONLY_USER;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO $READONLY_USER;
GRANT SELECT ON ALL SEQUENCES IN SCHEMA public TO $READONLY_USER;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO $READONLY_USER;
SQL
fi

echo "User $READONLY_USER ready. Connection: postgresql://$READONLY_USER:***@$DB_HOST:$DB_PORT/$DB_NAME"
