# Generated by Django 5.1.3 on 2025-08-07 13:04

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("payment", "0032_alter_customerdepositinstruction_system_type_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BlackListEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "participation_type",
                    models.CharField(
                        choices=[
                            ("WALLET", "Wallet"),
                            ("MERCHANT", "Merchant"),
                            ("GLOBAL", "Global"),
                        ],
                        help_text="The scope of this entry: Wallet, Merchant, or Global.",
                        max_length=10,
                        verbose_name="Participation Type",
                    ),
                ),
                (
                    "time_added",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Time Added"
                    ),
                ),
                (
                    "valid_for",
                    models.CharField(
                        choices=[
                            ("24H", "24 hours"),
                            ("168H", "7 days"),
                            ("720H", "30 days"),
                            ("PERMANENT", "Permanent"),
                        ],
                        max_length=10,
                        verbose_name="Valid For",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="The exact expiration time of the entry.",
                        null=True,
                        verbose_name="Expires At",
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True,
                        help_text="The reason for adding the entry to the list.",
                        verbose_name="Reason",
                    ),
                ),
                (
                    "operation_type",
                    models.CharField(
                        choices=[
                            ("ALL", "All"),
                            ("DEPOSIT", "Deposit"),
                            ("WITHDRAWAL", "Withdrawal"),
                        ],
                        default="ALL",
                        max_length=10,
                        verbose_name="Operation Type",
                    ),
                ),
                (
                    "risk_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="The user's risk score at the time of addition.",
                        max_digits=5,
                        null=True,
                        verbose_name="Risk Score",
                    ),
                ),
                (
                    "customer_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Customer Name",
                    ),
                ),
                (
                    "customer_wallet_id",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Customer Wallet ID",
                    ),
                ),
                (
                    "masked_pan",
                    models.CharField(
                        blank=True, max_length=19, null=True, verbose_name="Masked PAN"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Phone"
                    ),
                ),
                (
                    "ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP Address"
                    ),
                ),
                (
                    "provider_code",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Provider Code",
                    ),
                ),
                (
                    "match_fields",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=30),
                        blank=True,
                        default=list,
                        help_text='List of fields to be used for matching in the OR model (e.g., ["email", "ip"]).',
                        size=None,
                    ),
                ),
                (
                    "added_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The user who added the entry. NULL if added by the system.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Added By",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        help_text="The customer to whom this entry applies.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="payment.customer",
                        verbose_name="Customer",
                    ),
                ),
                (
                    "merchant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Link to a merchant, if participation type is Merchant.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="payment.merchant",
                        verbose_name="Merchant",
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        blank=True,
                        help_text="Link to a wallet, if participation type is Wallet.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="payment.wallet",
                        verbose_name="Wallet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Black List Entry",
                "verbose_name_plural": "Black List Entries",
            },
        ),
        migrations.CreateModel(
            name="GrayListEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "participation_type",
                    models.CharField(
                        choices=[
                            ("WALLET", "Wallet"),
                            ("MERCHANT", "Merchant"),
                            ("GLOBAL", "Global"),
                        ],
                        help_text="The scope of this entry: Wallet, Merchant, or Global.",
                        max_length=10,
                        verbose_name="Participation Type",
                    ),
                ),
                (
                    "time_added",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Time Added"
                    ),
                ),
                (
                    "valid_for",
                    models.CharField(
                        choices=[
                            ("24H", "24 hours"),
                            ("168H", "7 days"),
                            ("720H", "30 days"),
                            ("PERMANENT", "Permanent"),
                        ],
                        max_length=10,
                        verbose_name="Valid For",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="The exact expiration time of the entry.",
                        null=True,
                        verbose_name="Expires At",
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True,
                        help_text="The reason for adding the entry to the list.",
                        verbose_name="Reason",
                    ),
                ),
                (
                    "operation_type",
                    models.CharField(
                        choices=[
                            ("ALL", "All"),
                            ("DEPOSIT", "Deposit"),
                            ("WITHDRAWAL", "Withdrawal"),
                        ],
                        default="ALL",
                        max_length=10,
                        verbose_name="Operation Type",
                    ),
                ),
                (
                    "risk_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="The user's risk score at the time of addition.",
                        max_digits=5,
                        null=True,
                        verbose_name="Risk Score",
                    ),
                ),
                (
                    "customer_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Customer Name",
                    ),
                ),
                (
                    "customer_wallet_id",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Customer Wallet ID",
                    ),
                ),
                (
                    "masked_pan",
                    models.CharField(
                        blank=True, max_length=19, null=True, verbose_name="Masked PAN"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Phone"
                    ),
                ),
                (
                    "ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP Address"
                    ),
                ),
                (
                    "provider_code",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Provider Code",
                    ),
                ),
                (
                    "match_fields",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=30),
                        blank=True,
                        default=list,
                        help_text='List of fields to be used for matching in the OR model (e.g., ["email", "ip"]).',
                        size=None,
                    ),
                ),
                (
                    "added_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The user who added the entry. NULL if added by the system.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Added By",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        help_text="The customer to whom this entry applies.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="payment.customer",
                        verbose_name="Customer",
                    ),
                ),
                (
                    "merchant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Link to a merchant, if participation type is Merchant.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="payment.merchant",
                        verbose_name="Merchant",
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        blank=True,
                        help_text="Link to a wallet, if participation type is Wallet.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="payment.wallet",
                        verbose_name="Wallet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Gray List Entry",
                "verbose_name_plural": "Gray List Entries",
            },
        ),
        migrations.CreateModel(
            name="MerchantBlackListEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "participation_type",
                    models.CharField(
                        choices=[
                            ("WALLET", "Wallet"),
                            ("MERCHANT", "Merchant"),
                            ("GLOBAL", "Global"),
                        ],
                        help_text="The scope of this entry: Wallet, Merchant, or Global.",
                        max_length=10,
                        verbose_name="Participation Type",
                    ),
                ),
                (
                    "time_added",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Time Added"
                    ),
                ),
                (
                    "valid_for",
                    models.CharField(
                        choices=[
                            ("24H", "24 hours"),
                            ("168H", "7 days"),
                            ("720H", "30 days"),
                            ("PERMANENT", "Permanent"),
                        ],
                        max_length=10,
                        verbose_name="Valid For",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="The exact expiration time of the entry.",
                        null=True,
                        verbose_name="Expires At",
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True,
                        help_text="The reason for adding the entry to the list.",
                        verbose_name="Reason",
                    ),
                ),
                (
                    "operation_type",
                    models.CharField(
                        choices=[
                            ("ALL", "All"),
                            ("DEPOSIT", "Deposit"),
                            ("WITHDRAWAL", "Withdrawal"),
                        ],
                        default="ALL",
                        max_length=10,
                        verbose_name="Operation Type",
                    ),
                ),
                (
                    "risk_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="The user's risk score at the time of addition.",
                        max_digits=5,
                        null=True,
                        verbose_name="Risk Score",
                    ),
                ),
                (
                    "customer_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Customer Name",
                    ),
                ),
                (
                    "customer_wallet_id",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Customer Wallet ID",
                    ),
                ),
                (
                    "masked_pan",
                    models.CharField(
                        blank=True, max_length=19, null=True, verbose_name="Masked PAN"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Phone"
                    ),
                ),
                (
                    "ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP Address"
                    ),
                ),
                (
                    "provider_code",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Provider Code",
                    ),
                ),
                (
                    "match_fields",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=30),
                        blank=True,
                        default=list,
                        help_text='List of fields to be used for matching in the OR model (e.g., ["email", "ip"]).',
                        size=None,
                    ),
                ),
                (
                    "added_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The user who added the entry. NULL if added by the system.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Added By",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        help_text="The customer to whom this entry applies.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="payment.customer",
                        verbose_name="Customer",
                    ),
                ),
                (
                    "merchant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Link to a merchant, if participation type is Merchant.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="payment.merchant",
                        verbose_name="Merchant",
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        blank=True,
                        help_text="Link to a wallet, if participation type is Wallet.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="payment.wallet",
                        verbose_name="Wallet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Merchant Black List Entry",
                "verbose_name_plural": "Merchant Black List Entries",
            },
        ),
        migrations.CreateModel(
            name="WhiteListEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "participation_type",
                    models.CharField(
                        choices=[
                            ("WALLET", "Wallet"),
                            ("MERCHANT", "Merchant"),
                            ("GLOBAL", "Global"),
                        ],
                        help_text="The scope of this entry: Wallet, Merchant, or Global.",
                        max_length=10,
                        verbose_name="Participation Type",
                    ),
                ),
                (
                    "time_added",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Time Added"
                    ),
                ),
                (
                    "valid_for",
                    models.CharField(
                        choices=[
                            ("24H", "24 hours"),
                            ("168H", "7 days"),
                            ("720H", "30 days"),
                            ("PERMANENT", "Permanent"),
                        ],
                        max_length=10,
                        verbose_name="Valid For",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="The exact expiration time of the entry.",
                        null=True,
                        verbose_name="Expires At",
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True,
                        help_text="The reason for adding the entry to the list.",
                        verbose_name="Reason",
                    ),
                ),
                (
                    "operation_type",
                    models.CharField(
                        choices=[
                            ("ALL", "All"),
                            ("DEPOSIT", "Deposit"),
                            ("WITHDRAWAL", "Withdrawal"),
                        ],
                        default="ALL",
                        max_length=10,
                        verbose_name="Operation Type",
                    ),
                ),
                (
                    "risk_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="The user's risk score at the time of addition.",
                        max_digits=5,
                        null=True,
                        verbose_name="Risk Score",
                    ),
                ),
                (
                    "customer_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Customer Name",
                    ),
                ),
                (
                    "customer_wallet_id",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Customer Wallet ID",
                    ),
                ),
                (
                    "masked_pan",
                    models.CharField(
                        blank=True, max_length=19, null=True, verbose_name="Masked PAN"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Phone"
                    ),
                ),
                (
                    "ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP Address"
                    ),
                ),
                (
                    "provider_code",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Provider Code",
                    ),
                ),
                (
                    "match_fields",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=30),
                        blank=True,
                        default=list,
                        help_text='List of fields to be used for matching in the OR model (e.g., ["email", "ip"]).',
                        size=None,
                    ),
                ),
                (
                    "added_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The user who added the entry. NULL if added by the system.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Added By",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        help_text="The customer to whom this entry applies.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="payment.customer",
                        verbose_name="Customer",
                    ),
                ),
                (
                    "merchant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Link to a merchant, if participation type is Merchant.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="payment.merchant",
                        verbose_name="Merchant",
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        blank=True,
                        help_text="Link to a wallet, if participation type is Wallet.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="payment.wallet",
                        verbose_name="Wallet",
                    ),
                ),
            ],
            options={
                "verbose_name": "White List Entry",
                "verbose_name_plural": "White List Entries",
            },
        ),
        migrations.CreateModel(
            name="RiskListHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "changed_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Changed At"
                    ),
                ),
                (
                    "changed_by_repr",
                    models.CharField(
                        help_text="String representation of user or 'System'",
                        max_length=255,
                        verbose_name="Changed By (repr)",
                    ),
                ),
                (
                    "change_type",
                    models.CharField(
                        choices=[
                            ("ADDED", "Added"),
                            ("EDITED", "Edited"),
                            ("REMOVED", "Removed"),
                        ],
                        max_length=10,
                        verbose_name="Change Type",
                    ),
                ),
                (
                    "changes",
                    models.JSONField(
                        default=dict,
                        help_text="Stores old and new values for fields",
                        verbose_name="Changes",
                    ),
                ),
                ("reason", models.TextField(blank=True, verbose_name="Reason")),
                (
                    "blacklist_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="risk_lists.blacklistentry",
                    ),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Changed By",
                    ),
                ),
                (
                    "graylist_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="risk_lists.graylistentry",
                    ),
                ),
                (
                    "merchant_bl_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="risk_lists.merchantblacklistentry",
                    ),
                ),
                (
                    "whitelist_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="risk_lists.whitelistentry",
                    ),
                ),
            ],
            options={
                "verbose_name": "Risk List History",
                "verbose_name_plural": "Risk Lists History",
                "ordering": ["-changed_at"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("blacklist_entry__isnull", True),
                                ("graylist_entry__isnull", True),
                                ("merchant_bl_entry__isnull", True),
                                ("whitelist_entry__isnull", False),
                            ),
                            models.Q(
                                ("blacklist_entry__isnull", False),
                                ("graylist_entry__isnull", True),
                                ("merchant_bl_entry__isnull", True),
                                ("whitelist_entry__isnull", True),
                            ),
                            models.Q(
                                ("blacklist_entry__isnull", True),
                                ("graylist_entry__isnull", False),
                                ("merchant_bl_entry__isnull", True),
                                ("whitelist_entry__isnull", True),
                            ),
                            models.Q(
                                ("blacklist_entry__isnull", True),
                                ("graylist_entry__isnull", True),
                                ("merchant_bl_entry__isnull", False),
                                ("whitelist_entry__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="only_one_list_entry_is_set",
                    )
                ],
            },
        ),
    ]
