# Generated by Django 5.1.3 on 2025-11-25 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0035_alter_eventlog_event_type_and_more"),
        ("risk_lists", "0002_remove_risklisthistory_blacklist_entry_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="risklistentry",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                help_text="The customer to whom this entry applies.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="payment.customer",
                verbose_name="Customer",
            ),
        ),
    ]
