# Generated by Django 5.1.3 on 2025-10-15 19:36
# SAFE MIGRATION
import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from rozert_pay.risk_lists.const import (
    ALLOWED_MATCH_FIELDS,
    ListType,
    OperationType,
    scope,
    ValidFor,
)


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0035_alter_eventlog_event_type_and_more"),
        ("risk_lists", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="risklisthistory",
            name="blacklist_entry",
        ),
        migrations.RemoveField(
            model_name="graylistentry",
            name="added_by",
        ),
        migrations.RemoveField(
            model_name="graylistentry",
            name="customer",
        ),
        migrations.RemoveField(
            model_name="graylistentry",
            name="merchant",
        ),
        migrations.RemoveField(
            model_name="graylistentry",
            name="wallet",
        ),
        migrations.RemoveField(
            model_name="risklisthistory",
            name="graylist_entry",
        ),
        migrations.RemoveField(
            model_name="merchantblacklistentry",
            name="added_by",
        ),
        migrations.RemoveField(
            model_name="merchantblacklistentry",
            name="customer",
        ),
        migrations.RemoveField(
            model_name="merchantblacklistentry",
            name="merchant",
        ),
        migrations.RemoveField(
            model_name="merchantblacklistentry",
            name="wallet",
        ),
        migrations.RemoveField(
            model_name="risklisthistory",
            name="merchant_bl_entry",
        ),
        migrations.RemoveField(
            model_name="risklisthistory",
            name="changed_by",
        ),
        migrations.RemoveField(
            model_name="risklisthistory",
            name="whitelist_entry",
        ),
        migrations.RemoveField(
            model_name="whitelistentry",
            name="added_by",
        ),
        migrations.RemoveField(
            model_name="whitelistentry",
            name="customer",
        ),
        migrations.RemoveField(
            model_name="whitelistentry",
            name="merchant",
        ),
        migrations.RemoveField(
            model_name="whitelistentry",
            name="wallet",
        ),
        migrations.CreateModel(
            name="RiskListEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "list_type",
                    models.CharField(
                        choices=ListType.choices,
                        db_index=True,
                        max_length=16,
                        verbose_name="List Type",
                    ),
                ),
                (
                    "participation_type",
                    models.CharField(
                        choices=scope.choices,
                        help_text="The scope of this entry.",
                        max_length=10,
                        verbose_name="Participation Type",
                    ),
                ),
                (
                    "time_added",
                    models.DateTimeField(auto_now_add=True, verbose_name="Time Added"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "valid_for",
                    models.CharField(
                        choices=ValidFor.choices,
                        max_length=10,
                        verbose_name="Valid For",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, db_index=True, null=True, verbose_name="Expires At"
                    ),
                ),
                ("reason", models.TextField(blank=True, verbose_name="Reason")),
                (
                    "operation_type",
                    models.CharField(
                        choices=OperationType.choices,
                        default="all",
                        max_length=10,
                        verbose_name="Operation Type",
                    ),
                ),
                (
                    "customer_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Customer Name",
                    ),
                ),
                (
                    "customer_wallet_id",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Customer Wallet ID",
                    ),
                ),
                (
                    "masked_pan",
                    models.CharField(
                        blank=True, max_length=19, null=True, verbose_name="Masked PAN"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Phone"
                    ),
                ),
                (
                    "ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP Address"
                    ),
                ),
                (
                    "provider_code",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Provider Code",
                    ),
                ),
                (
                    "match_fields",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[(f.value, f.value) for f in ALLOWED_MATCH_FIELDS],
                            max_length=30,
                        ),
                        blank=True,
                        default=list,
                        help_text="Fields actually used for matching.(if all are selected, only non-empty values are stored). If empty, the entry will not match.",
                        size=None,
                    ),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                (
                    "delete_reason",
                    models.TextField(
                        blank=True, null=True, verbose_name="Deletion Reason"
                    ),
                ),
                (
                    "added_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Added By",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        help_text="The customer to whom this entry applies.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="payment.customer",
                        verbose_name="Customer",
                    ),
                ),
                (
                    "merchant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Link to a merchant, if participation type is Merchant.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="payment.merchant",
                        verbose_name="Merchant",
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        blank=True,
                        help_text="Link to a wallet, if participation type is Wallet.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="payment.wallet",
                        verbose_name="Wallet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Risk List Entry",
                "verbose_name_plural": "Risk List Entries",
                "ordering": ["-time_added"],
            },
        ),
        migrations.DeleteModel(
            name="BlackListEntry",
        ),
        migrations.DeleteModel(
            name="GrayListEntry",
        ),
        migrations.DeleteModel(
            name="MerchantBlackListEntry",
        ),
        migrations.DeleteModel(
            name="RiskListHistory",
        ),
        migrations.DeleteModel(
            name="WhiteListEntry",
        ),
        migrations.CreateModel(
            name="BlackListEntry",
            fields=[],
            options={
                "verbose_name": "Black List Entry",
                "verbose_name_plural": "Black List Entries",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("risk_lists.risklistentry",),
        ),
        migrations.CreateModel(
            name="GrayListEntry",
            fields=[],
            options={
                "verbose_name": "Gray List Entry",
                "verbose_name_plural": "Gray List Entries",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("risk_lists.risklistentry",),
        ),
        migrations.CreateModel(
            name="MerchantBlackListEntry",
            fields=[],
            options={
                "verbose_name": "Merchant Black List Entry",
                "verbose_name_plural": "Merchant Black List Entries",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("risk_lists.risklistentry",),
        ),
        migrations.CreateModel(
            name="WhiteListEntry",
            fields=[],
            options={
                "verbose_name": "White List Entry",
                "verbose_name_plural": "White List Entries",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("risk_lists.risklistentry",),
        ),
    ]
