# Generated by Django 5.1.3 on 2026-02-05 09:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0044_paymenttransaction_amount2"),
        ("risk_lists", "0003_alter_risklistentry_customer"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="risklistentry",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Risk List Entry",
                "verbose_name_plural": "Risk List Entries",
            },
        ),
        migrations.RenameField(
            model_name="risklistentry",
            old_name="time_added",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="risklistentry",
            old_name="time_added",
            new_name="created_at",
        ),
        migrations.RemoveField(
            model_name="risklistentry",
            name="participation_type",
        ),
        migrations.AddField(
            model_name="risklistentry",
            name="scope",
            field=models.CharField(
                choices=[
                    ("WALLET", "Wallet"),
                    ("MERCHANT", "Merchant"),
                    ("GLOBAL", "Global"),
                ],
                default=django.utils.timezone.now,
                max_length=10,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="risklistentry",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                help_text="The customer to whom this entry applies.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="payment.customer",
            ),
        ),
        migrations.AlterField(
            model_name="risklistentry",
            name="merchant",
            field=models.ForeignKey(
                blank=True,
                help_text="Link to a merchant, if a scope is Merchant.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="payment.merchant",
            ),
        ),
        migrations.AlterField(
            model_name="risklistentry",
            name="wallet",
            field=models.ForeignKey(
                blank=True,
                help_text="Link to a wallet, if a scope is Wallet.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="payment.wallet",
            ),
        ),
    ]
