# Generated by Django 5.1.3 on 2026-02-05 09:54
# SAFE MIGRATION

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models
from django.conf import settings


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0044_paymenttransaction_amount2"),
        ("risk_lists", "0003_alter_risklistentry_customer"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="risklistentry",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Risk List Entry",
                "verbose_name_plural": "Risk List Entries",
            },
        ),
        migrations.RenameField(
            model_name="risklistentry",
            old_name="time_added",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="risklistentry",
            old_name="participation_type",
            new_name="scope",
        ),
        migrations.AddField(
            model_name="risklistentry",
            name="transaction",
            field=models.ForeignKey(
                blank=True,
                help_text="Transaction which triggered the list entry.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="payment.paymenttransaction",
            ),
        ),
        migrations.AlterField(
            model_name="risklistentry",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                help_text="The customer to whom this entry applies.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="payment.customer",
            ),
        ),
        migrations.AlterField(
            model_name="risklistentry",
            name="merchant",
            field=models.ForeignKey(
                blank=True,
                help_text="Link to a merchant, if a scope is Merchant.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="payment.merchant",
            ),
        ),
        migrations.AlterField(
            model_name="risklistentry",
            name="wallet",
            field=models.ForeignKey(
                blank=True,
                help_text="Link to a wallet, if a scope is Wallet.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="payment.wallet",
            ),
        ),
        migrations.AlterField(
            model_name="risklistentry",
            name="added_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="risklistentry",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="risklistentry",
            name="customer_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="risklistentry",
            name="delete_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="risklistentry",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="risklistentry",
            name="expires_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="risklistentry",
            name="operation_type",
            field=models.CharField(
                choices=[
                    ("all", "All"),
                    ("deposit", "Deposit"),
                    ("withdrawal", "Withdrawal"),
                ],
                default="all",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="risklistentry",
            name="phone",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="risklistentry",
            name="provider_code",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="risklistentry",
            name="reason",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="risklistentry",
            name="scope",
            field=models.CharField(
                choices=[
                    ("WALLET", "Wallet"),
                    ("MERCHANT", "Merchant"),
                    ("GLOBAL", "Global"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="risklistentry",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="risklistentry",
            name="valid_for",
            field=models.CharField(
                choices=[
                    ("24H", "24 hours"),
                    ("168H", "7 days"),
                    ("720H", "30 days"),
                    ("PERMANENT", "Permanent"),
                ],
                max_length=10,
            ),
        ),
    ]
