# Generated by Django 5.1.3 on 2026-02-05 12:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("risk_lists", "0004_alter_risklistentry_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="risklistentry",
            name="added_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="risklistentry",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="risklistentry",
            name="customer_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="risklistentry",
            name="delete_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="risklistentry",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="risklistentry",
            name="expires_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="risklistentry",
            name="operation_type",
            field=models.CharField(
                choices=[
                    ("all", "All"),
                    ("deposit", "Deposit"),
                    ("withdrawal", "Withdrawal"),
                ],
                default="all",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="risklistentry",
            name="phone",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="risklistentry",
            name="provider_code",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="risklistentry",
            name="reason",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="risklistentry",
            name="scope",
            field=models.CharField(
                choices=[
                    ("WALLET", "Wallet"),
                    ("MERCHANT", "Merchant"),
                    ("GLOBAL", "Global"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="risklistentry",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="risklistentry",
            name="valid_for",
            field=models.CharField(
                choices=[
                    ("24H", "24 hours"),
                    ("168H", "7 days"),
                    ("720H", "30 days"),
                    ("PERMANENT", "Permanent"),
                ],
                max_length=10,
            ),
        ),
    ]
