# Generated by Django 5.1.3 on 2025-06-19 09:46

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("payment", "0027_alter_eventlog_event_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerLimit",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "active",
                    models.BooleanField(
                        default=True, help_text="Статус лимита, включен или выключен"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Описание лимита заданное пользователем"
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        choices=[("1h", "1 Hour"), ("24h", "24 Hours")], max_length=255
                    ),
                ),
                (
                    "max_successful_operations",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Максимальное количество успешных операций за период",
                    ),
                ),
                (
                    "max_failed_operations",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Максимальное количество неуспешных операций за период",
                    ),
                ),
                (
                    "min_operation_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Минимальная сумма, разрешенная для одной операции",
                        max_digits=20,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Минимальная сумма одной операции",
                    ),
                ),
                (
                    "max_operation_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Максимальная сумма, разрешенная для одной операции",
                        max_digits=20,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Максимальная сумма одной операции",
                    ),
                ),
                (
                    "total_successful_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Максимальная общая сумма всех успешных операций за указанный период",
                        max_digits=20,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Общая сумма успешных операций за период",
                    ),
                ),
                (
                    "decline_on_exceed",
                    models.BooleanField(
                        default=False,
                        help_text="Включает отклонение операции при превышении лимита",
                        verbose_name="Отклонять при превышении",
                    ),
                ),
                (
                    "is_critical",
                    models.BooleanField(
                        default=False,
                        help_text="Переводит алерт в категорию критических уведомлений",
                        verbose_name="Критический лимит",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client_limits",
                        to="payment.customer",
                        verbose_name="Клиент",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MerchantLimit",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "active",
                    models.BooleanField(
                        default=True, help_text="Статус лимита, включен или выключен"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Описание лимита заданное пользователем"
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("merchant", "Merchant"),
                            ("wallet", "Merchant Wallet"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "limit_type",
                    models.CharField(
                        choices=[
                            (
                                "max_successful_deposits",
                                "Максимальное количество успешных депозитов за период",
                            ),
                            (
                                "max_decline_percent",
                                "Максимальный процент деклайнов за период",
                            ),
                            (
                                "min_single_operation",
                                "Минимальная сумма одной операции",
                            ),
                            (
                                "max_single_operation",
                                "Максимальная сумма одной операции",
                            ),
                            (
                                "total_deposits_period",
                                "Общая сумма депозитов за период",
                            ),
                            (
                                "total_withdrawals_period",
                                "Общий объем выплат за период",
                            ),
                            (
                                "max_withdrawal_to_deposit_ratio",
                                "Максимальный процент выплат к депозитам за период",
                            ),
                            (
                                "max_operations_burst",
                                "Максимальное количество любых операций за короткий период",
                            ),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        choices=[("1h", "1 Hour"), ("24h", "24 Hours")],
                        default="24h",
                        max_length=3,
                    ),
                ),
                (
                    "max_operations",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Максимальное количество операций",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "max_decline_percent",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Максимальный процент деклайнов",
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "min_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Минимальная сумма",
                        max_digits=15,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "max_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Максимальная сумма",
                        max_digits=15,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Общая сумма за период",
                        max_digits=15,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "max_ratio",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Максимальный процент",
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "burst_minutes",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Количество минут для проверки всплеска операций",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(60),
                        ],
                    ),
                ),
                (
                    "decline_on_exceed",
                    models.BooleanField(
                        default=False,
                        help_text="Отклонять операцию при превышении лимита",
                    ),
                ),
                (
                    "is_critical",
                    models.BooleanField(
                        default=False,
                        help_text="Переводить алерт в категорию критических уведомлений",
                    ),
                ),
                (
                    "merchant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="merchant_limits",
                        to="payment.merchant",
                        verbose_name="Merchant",
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="merchant_limits",
                        to="payment.wallet",
                        verbose_name="Wallet",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LimitAlerts",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("extra", models.JSONField(default=dict)),
                (
                    "customer_limit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="limit_trigger_logs",
                        to="limits.customerlimit",
                        verbose_name="Customer Limit",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        help_text="Transaction that triggered the limit",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="limit_trigger_logs",
                        to="payment.paymenttransaction",
                        verbose_name="Transaction",
                    ),
                ),
                (
                    "merchant_limit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="limit_trigger_logs",
                        to="limits.merchantlimit",
                        verbose_name="Merchant Limit",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
