# Generated by Django 5.1.3 on 2025-08-25 12:41

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("limits", "0001_initial"),
        ("payment", "0033_alter_merchantgroup_queue"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customerlimit",
            name="active",
            field=models.BooleanField(
                default=True, help_text="Limit status, enabled or disabled"
            ),
        ),
        migrations.AlterField(
            model_name="customerlimit",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="client_limits",
                to="payment.customer",
                verbose_name="Client",
            ),
        ),
        migrations.AlterField(
            model_name="customerlimit",
            name="decline_on_exceed",
            field=models.BooleanField(
                default=False,
                help_text="Enable automatic rejection of operations that exceed the limit",
                verbose_name="Reject on limit exceed",
            ),
        ),
        migrations.AlterField(
            model_name="customerlimit",
            name="description",
            field=models.TextField(
                blank=True, help_text="Limit description set by the user"
            ),
        ),
        migrations.AlterField(
            model_name="customerlimit",
            name="is_critical",
            field=models.BooleanField(
                default=False,
                help_text="Escalates the alert to a critical notification",
                verbose_name="Critical limit",
            ),
        ),
        migrations.AlterField(
            model_name="customerlimit",
            name="max_failed_operations",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                verbose_name="Maximum number of failed operations per period",
            ),
        ),
        migrations.AlterField(
            model_name="customerlimit",
            name="max_operation_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Maximum amount allowed for a single operation",
                max_digits=20,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                verbose_name="Maximum amount for a single operation",
            ),
        ),
        migrations.AlterField(
            model_name="customerlimit",
            name="max_successful_operations",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                verbose_name="Maximum number of successful operations per period",
            ),
        ),
        migrations.AlterField(
            model_name="customerlimit",
            name="min_operation_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Minimum amount allowed for a single operation",
                max_digits=20,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                verbose_name="Minimum amount for a single operation",
            ),
        ),
        migrations.AlterField(
            model_name="customerlimit",
            name="total_successful_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Maximum total amount of all successful operations for the specified period",
                max_digits=20,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                verbose_name="Total amount of successful operations per period",
            ),
        ),
        migrations.AlterField(
            model_name="merchantlimit",
            name="active",
            field=models.BooleanField(
                default=True, help_text="Status of the limit: enabled or disabled"
            ),
        ),
        migrations.AlterField(
            model_name="merchantlimit",
            name="burst_minutes",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Number of minutes for checking operation burst",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(60),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="merchantlimit",
            name="decline_on_exceed",
            field=models.BooleanField(
                default=False, help_text="Decline operation if limit is exceeded"
            ),
        ),
        migrations.AlterField(
            model_name="merchantlimit",
            name="description",
            field=models.TextField(
                blank=True, help_text="User-defined limit description"
            ),
        ),
        migrations.AlterField(
            model_name="merchantlimit",
            name="is_critical",
            field=models.BooleanField(
                default=False,
                help_text="Escalate alert to critical notifications category",
            ),
        ),
        migrations.AlterField(
            model_name="merchantlimit",
            name="limit_type",
            field=models.CharField(
                choices=[
                    (
                        "max_successful_deposits",
                        "Maximum number of successful deposits per period",
                    ),
                    (
                        "max_overall_decline_percent",
                        "Maximum percentage of declines per period",
                    ),
                    (
                        "max_withdrawal_decline_percent",
                        "Maximum percentage of withdrawal declines per period",
                    ),
                    (
                        "max_deposit_decline_percent",
                        "Maximum percentage of deposit declines per period",
                    ),
                    (
                        "min_amount_single_operation",
                        "Minimum amount of a single operation",
                    ),
                    (
                        "max_amount_single_operation",
                        "Maximum amount of a single operation",
                    ),
                    (
                        "total_amount_deposits_period",
                        "Total amount of deposits per period",
                    ),
                    (
                        "total_amount_withdrawals_period",
                        "Total amount of withdrawals per period",
                    ),
                    (
                        "max_withdrawal_to_deposit_ratio",
                        "Maximum percentage of withdrawals to deposits per period",
                    ),
                    (
                        "max_operations_burst",
                        "Maximum number of any operations in a short period",
                    ),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="merchantlimit",
            name="max_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Maximum amount",
                max_digits=15,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="merchantlimit",
            name="max_deposit_decline_percent",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Maximum percentage of declined deposits",
                max_digits=5,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="merchantlimit",
            name="max_operations",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Maximum number of operations",
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AlterField(
            model_name="merchantlimit",
            name="max_overall_decline_percent",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Maximum percentage of all declines",
                max_digits=5,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="merchantlimit",
            name="max_ratio",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Maximum percentage",
                max_digits=5,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="merchantlimit",
            name="max_withdrawal_decline_percent",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Maximum percentage of declined withdrawals",
                max_digits=5,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="merchantlimit",
            name="min_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Minimum amount",
                max_digits=15,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="merchantlimit",
            name="total_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Total amount per period",
                max_digits=15,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
