# Generated by Django 5.1.3 on 2025-12-01 14:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        (
            "limits",
            "0005_globalriskmerchantlimit_alter_customerlimit_category_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="customerlimit",
            name="active",
            field=models.BooleanField(
                default=True, help_text="Status of the limit: enabled or disabled"
            ),
        ),
        migrations.AlterField(
            model_name="customerlimit",
            name="decline_on_exceed",
            field=models.BooleanField(
                default=False, help_text="Decline operation if limit is exceeded"
            ),
        ),
        migrations.AlterField(
            model_name="customerlimit",
            name="description",
            field=models.TextField(
                blank=True, help_text="User-defined limit description"
            ),
        ),
        migrations.AlterField(
            model_name="customerlimit",
            name="is_critical",
            field=models.BooleanField(
                default=False,
                help_text="Escalate alert to critical notifications category",
            ),
        ),
        migrations.AlterField(
            model_name="customerlimit",
            name="notification_groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="User groups that will receive notifications about this alert.",
                related_name="%(class)s_limits_to_notify",
                to="auth.group",
            ),
        ),
        migrations.AlterField(
            model_name="merchantlimit",
            name="notification_groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="User groups that will receive notifications about this alert.",
                related_name="%(class)s_limits_to_notify",
                to="auth.group",
            ),
        ),
        migrations.AlterField(
            model_name="merchantlimit",
            name="period",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1h", "1 Hour"),
                    ("24h", "24 Hours"),
                    ("beginning_of_hour", "Beginning of Hour"),
                    ("beginning_of_day", "Beginning of Day"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
